# Build all services
filegroup(
    name = "all_services",
    srcs = [
        "//admin_service:admin_service_server",
        "//gateway_service:gateway_service_server",
        "//slice_service:slice_service_server",
        "//gs_cli:gs_cli",
    ],
    visibility = ["//visibility:public"],
)

# Run all tests
test_suite(
    name = "all_tests",
    tests = [
        "//internal/storage:storage_test",
        "//workflow_test:integration_test",
    ],
)
