import {
  apiBaseUrl,
  encodeBase64,
  fetchWithAuth,
  readErrorMessage,
} from './client.js';

function decodeBase64(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function normalizeAgentPublicKeyInput(input) {
  const trimmed = String(input || '').trim();
  if (!trimmed) {
    throw new Error('Public key is required.');
  }

  const rawBase64 = trimmed
    .replace('-----BEGIN PUBLIC KEY-----', '')
    .replace('-----END PUBLIC KEY-----', '')
    .replace(/\s+/g, '');
  const bytes = decodeBase64(rawBase64);
  if (bytes.length === 32) {
    return encodeBase64(bytes);
  }

  const expectedPrefix = [0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x03, 0x21, 0x00];
  const matchesPrefix = bytes.length === expectedPrefix.length + 32 && expectedPrefix.every((value, index) => bytes[index] === value);
  if (matchesPrefix) {
    return encodeBase64(bytes.slice(expectedPrefix.length));
  }

  throw new Error('Unsupported public key format. Paste the .pub file generated by gs auth keygen or raw base64 ed25519 public key bytes.');
}

export async function fetchAgentKeys() {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent keys'));
  }
  const payload = await response.json();
  return payload?.keys || [];
}

export async function createAgentKey({ name, publicKeyText }) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name,
      algorithm: 'ed25519',
      publicKey: normalizeAgentPublicKeyInput(publicKeyText),
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to add agent key'));
  }
  return response.json();
}

export async function revokeAgentKey(keyId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys/${encodeURIComponent(keyId)}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to revoke agent key'));
  }
}

export async function listAgentSessions(sliceId, { limit = 50 } = {}) {
  const query = new URLSearchParams();
  query.set('slice_id', String(sliceId || '').trim());
  if (typeof limit === 'number' && limit > 0) {
    query.set('limit', String(limit));
  }
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions?${query.toString()}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent sessions'));
  }
  const payload = await response.json();
  return payload?.sessions || [];
}

export async function listAgentRunners({ limit = 50, includeOffline = false } = {}) {
  const query = new URLSearchParams();
  if (typeof limit === 'number' && limit > 0) {
    query.set('limit', String(limit));
  }
  if (includeOffline) {
    query.set('includeOffline', 'true');
  }
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-runners?${query.toString()}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent runners'));
  }
  const payload = await response.json();
  return payload?.runners || [];
}

export async function waitForAgentRunnerUpdates({ timeoutMs = 25000, signal } = {}) {
  const query = new URLSearchParams();
  if (typeof timeoutMs === 'number' && timeoutMs > 0) {
    query.set('timeoutMs', String(Math.round(timeoutMs)));
  }
  const response = await fetchWithAuth(`${apiBaseUrl}/ws/agent-runners?${query.toString()}`, {
    signal,
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to watch agent runners'));
  }
  const payload = await response.json();
  return Boolean(payload?.changed);
}

export async function createAgentSession(sliceId, { runnerId = '', environment = '', agentType = '' } = {}) {
  const body = {
    sliceId,
  };
  if (runnerId) {
    body.runnerId = runnerId;
  }
  if (environment) {
    body.environment = environment;
  }
  if (agentType) {
    body.agentType = agentType;
  }
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to create agent session'));
  }
  return response.json();
}

export async function listAgentSessionEvents(sessionId, { sinceSeq = 0, limit = 200, tail = 0 } = {}) {
  const query = new URLSearchParams();
  if (typeof tail === 'number' && tail > 0) {
    query.set('tail', String(tail));
  } else {
    query.set('sinceSeq', String(sinceSeq || 0));
  }
  if (typeof limit === 'number' && limit > 0) {
    query.set('limit', String(limit));
  }
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions/${encodeURIComponent(sessionId)}/events?${query.toString()}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent conversation'));
  }
  return response.json();
}

export async function mintAgentSessionToken(sessionId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions/${encodeURIComponent(sessionId)}/token`, {
    method: 'POST',
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to connect to agent conversation'));
  }
  return response.json();
}

function encodeJSONPayload(payload = {}) {
  const raw = JSON.stringify(payload || {});
  return encodeBase64(new TextEncoder().encode(raw));
}

export async function appendAgentSessionEvent(sessionId, { stream, type, payload = {} }) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions/${encodeURIComponent(sessionId)}/events`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      stream,
      type,
      payload: encodeJSONPayload(payload),
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to append agent event'));
  }
  return response.json();
}

export async function requestAgentRunnerRestart(sessionId, { upgrade = true, reason = 'web_ui' } = {}) {
  return appendAgentSessionEvent(sessionId, {
    stream: 'control',
    type: 'local_runner_restart_requested',
    payload: {
      upgrade: Boolean(upgrade),
      reason,
    },
  });
}

function createAgentRequestId(prefix = 'req') {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

export async function requestAgentSessionLocalChanges(sessionId, { limit = 100, includeDiffs = false } = {}) {
  const requestId = createAgentRequestId('local_changes');
  const response = await appendAgentSessionEvent(sessionId, {
    stream: 'control',
    type: 'local_changes_requested',
    payload: {
      requestId,
      limit,
      includeDiffs: Boolean(includeDiffs),
    },
  });
  return { requestId, response };
}

export async function requestAgentSessionChangesetExport(sessionId, { message = '', files = [] } = {}) {
  const requestId = createAgentRequestId('changeset_export');
  const response = await appendAgentSessionEvent(sessionId, {
    stream: 'control',
    type: 'changeset_export_requested',
    payload: {
      requestId,
      message,
      files,
    },
  });
  return { requestId, response };
}

export async function sendAgentSessionInput(sessionId, text) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions/${encodeURIComponent(sessionId)}/input`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to send agent input'));
  }
  return response.json();
}

export async function getAgentCapabilities() {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/agent-sessions/capabilities`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent capabilities'));
  }
  return response.json();
}
