// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: slice_service.proto

package slicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_BLOB      ObjectType = 0
	ObjectType_TREE      ObjectType = 1
	ObjectType_COMMIT    ObjectType = 2
	ObjectType_SLICE_DEF ObjectType = 3
	ObjectType_CHANGESET ObjectType = 4
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "BLOB",
		1: "TREE",
		2: "COMMIT",
		3: "SLICE_DEF",
		4: "CHANGESET",
	}
	ObjectType_value = map[string]int32{
		"BLOB":      0,
		"TREE":      1,
		"COMMIT":    2,
		"SLICE_DEF": 3,
		"CHANGESET": 4,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_slice_service_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_slice_service_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{0}
}

type MergeStatus int32

const (
	MergeStatus_MERGE_STATUS_SUCCESS  MergeStatus = 0
	MergeStatus_MERGE_STATUS_CONFLICT MergeStatus = 1
	MergeStatus_MERGE_STATUS_ERROR    MergeStatus = 2
)

// Enum value maps for MergeStatus.
var (
	MergeStatus_name = map[int32]string{
		0: "MERGE_STATUS_SUCCESS",
		1: "MERGE_STATUS_CONFLICT",
		2: "MERGE_STATUS_ERROR",
	}
	MergeStatus_value = map[string]int32{
		"MERGE_STATUS_SUCCESS":  0,
		"MERGE_STATUS_CONFLICT": 1,
		"MERGE_STATUS_ERROR":    2,
	}
)

func (x MergeStatus) Enum() *MergeStatus {
	p := new(MergeStatus)
	*p = x
	return p
}

func (x MergeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_slice_service_proto_enumTypes[1].Descriptor()
}

func (MergeStatus) Type() protoreflect.EnumType {
	return &file_slice_service_proto_enumTypes[1]
}

func (x MergeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeStatus.Descriptor instead.
func (MergeStatus) EnumDescriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{1}
}

type RebaseStatus int32

const (
	RebaseStatus_REBASE_STATUS_SUCCESS     RebaseStatus = 0
	RebaseStatus_REBASE_STATUS_CONFLICT    RebaseStatus = 1
	RebaseStatus_REBASE_STATUS_NEEDS_MERGE RebaseStatus = 2
	RebaseStatus_REBASE_STATUS_ERROR       RebaseStatus = 3
)

// Enum value maps for RebaseStatus.
var (
	RebaseStatus_name = map[int32]string{
		0: "REBASE_STATUS_SUCCESS",
		1: "REBASE_STATUS_CONFLICT",
		2: "REBASE_STATUS_NEEDS_MERGE",
		3: "REBASE_STATUS_ERROR",
	}
	RebaseStatus_value = map[string]int32{
		"REBASE_STATUS_SUCCESS":     0,
		"REBASE_STATUS_CONFLICT":    1,
		"REBASE_STATUS_NEEDS_MERGE": 2,
		"REBASE_STATUS_ERROR":       3,
	}
)

func (x RebaseStatus) Enum() *RebaseStatus {
	p := new(RebaseStatus)
	*p = x
	return p
}

func (x RebaseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RebaseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_slice_service_proto_enumTypes[2].Descriptor()
}

func (RebaseStatus) Type() protoreflect.EnumType {
	return &file_slice_service_proto_enumTypes[2]
}

func (x RebaseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RebaseStatus.Descriptor instead.
func (RebaseStatus) EnumDescriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{2}
}

type ChangesetStatus int32

const (
	ChangesetStatus_PENDING  ChangesetStatus = 0
	ChangesetStatus_APPROVED ChangesetStatus = 1
	ChangesetStatus_REJECTED ChangesetStatus = 2
	ChangesetStatus_MERGED   ChangesetStatus = 3
)

// Enum value maps for ChangesetStatus.
var (
	ChangesetStatus_name = map[int32]string{
		0: "PENDING",
		1: "APPROVED",
		2: "REJECTED",
		3: "MERGED",
	}
	ChangesetStatus_value = map[string]int32{
		"PENDING":  0,
		"APPROVED": 1,
		"REJECTED": 2,
		"MERGED":   3,
	}
)

func (x ChangesetStatus) Enum() *ChangesetStatus {
	p := new(ChangesetStatus)
	*p = x
	return p
}

func (x ChangesetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangesetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_slice_service_proto_enumTypes[3].Descriptor()
}

func (ChangesetStatus) Type() protoreflect.EnumType {
	return &file_slice_service_proto_enumTypes[3]
}

func (x ChangesetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangesetStatus.Descriptor instead.
func (ChangesetStatus) EnumDescriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{3}
}

type ReviewStatus int32

const (
	ReviewStatus_READY_FOR_MERGE ReviewStatus = 0
	ReviewStatus_NEEDS_REBASE    ReviewStatus = 1
	ReviewStatus_HAS_CONFLICTS   ReviewStatus = 2
)

// Enum value maps for ReviewStatus.
var (
	ReviewStatus_name = map[int32]string{
		0: "READY_FOR_MERGE",
		1: "NEEDS_REBASE",
		2: "HAS_CONFLICTS",
	}
	ReviewStatus_value = map[string]int32{
		"READY_FOR_MERGE": 0,
		"NEEDS_REBASE":    1,
		"HAS_CONFLICTS":   2,
	}
)

func (x ReviewStatus) Enum() *ReviewStatus {
	p := new(ReviewStatus)
	*p = x
	return p
}

func (x ReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_slice_service_proto_enumTypes[4].Descriptor()
}

func (ReviewStatus) Type() protoreflect.EnumType {
	return &file_slice_service_proto_enumTypes[4]
}

func (x ReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewStatus.Descriptor instead.
func (ReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{4}
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	CommitHash    string                 `protobuf:"bytes,2,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_slice_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CheckoutRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *SliceManifest         `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	Files         []*FileContent         `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_slice_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutResponse) GetManifest() *SliceManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *CheckoutResponse) GetFiles() []*FileContent {
	if x != nil {
		return x.Files
	}
	return nil
}

type SliceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	FileMetadata  []*FileMetadata        `protobuf:"bytes,2,rep,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceManifest) Reset() {
	*x = SliceManifest{}
	mi := &file_slice_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceManifest) ProtoMessage() {}

func (x *SliceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceManifest.ProtoReflect.Descriptor instead.
func (*SliceManifest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{2}
}

func (x *SliceManifest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *SliceManifest) GetFileMetadata() []*FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,5,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_slice_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{3}
}

func (x *FileMetadata) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileMetadata) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_slice_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileContent) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CheckoutChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*CheckoutChunk_Manifest
	//	*CheckoutChunk_File
	Chunk         isCheckoutChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutChunk) Reset() {
	*x = CheckoutChunk{}
	mi := &file_slice_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutChunk) ProtoMessage() {}

func (x *CheckoutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutChunk.ProtoReflect.Descriptor instead.
func (*CheckoutChunk) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckoutChunk) GetChunk() isCheckoutChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *CheckoutChunk) GetManifest() *SliceManifest {
	if x != nil {
		if x, ok := x.Chunk.(*CheckoutChunk_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *CheckoutChunk) GetFile() *FileContent {
	if x != nil {
		if x, ok := x.Chunk.(*CheckoutChunk_File); ok {
			return x.File
		}
	}
	return nil
}

type isCheckoutChunk_Chunk interface {
	isCheckoutChunk_Chunk()
}

type CheckoutChunk_Manifest struct {
	Manifest *SliceManifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type CheckoutChunk_File struct {
	File *FileContent `protobuf:"bytes,2,opt,name=file,proto3,oneof"`
}

func (*CheckoutChunk_Manifest) isCheckoutChunk_Chunk() {}

func (*CheckoutChunk_File) isCheckoutChunk_Chunk() {}

type CreateChangesetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SliceId        string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	BaseCommitHash string                 `protobuf:"bytes,2,opt,name=base_commit_hash,json=baseCommitHash,proto3" json:"base_commit_hash,omitempty"`
	Objects        []*Object              `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	ModifiedFiles  []string               `protobuf:"bytes,4,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`
	Author         string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateChangesetRequest) Reset() {
	*x = CreateChangesetRequest{}
	mi := &file_slice_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChangesetRequest) ProtoMessage() {}

func (x *CreateChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChangesetRequest.ProtoReflect.Descriptor instead.
func (*CreateChangesetRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateChangesetRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CreateChangesetRequest) GetBaseCommitHash() string {
	if x != nil {
		return x.BaseCommitHash
	}
	return ""
}

func (x *CreateChangesetRequest) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *CreateChangesetRequest) GetModifiedFiles() []string {
	if x != nil {
		return x.ModifiedFiles
	}
	return nil
}

func (x *CreateChangesetRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateChangesetRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	ChangesetHash string                 `protobuf:"bytes,2,opt,name=changeset_hash,json=changesetHash,proto3" json:"changeset_hash,omitempty"`
	Status        ChangesetStatus        `protobuf:"varint,3,opt,name=status,proto3,enum=slice.v1.ChangesetStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChangesetResponse) Reset() {
	*x = CreateChangesetResponse{}
	mi := &file_slice_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChangesetResponse) ProtoMessage() {}

func (x *CreateChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChangesetResponse.ProtoReflect.Descriptor instead.
func (*CreateChangesetResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateChangesetResponse) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *CreateChangesetResponse) GetChangesetHash() string {
	if x != nil {
		return x.ChangesetHash
	}
	return ""
}

func (x *CreateChangesetResponse) GetStatus() ChangesetStatus {
	if x != nil {
		return x.Status
	}
	return ChangesetStatus_PENDING
}

type ChangesetChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Chunk:
	//
	//	*ChangesetChunk_Metadata
	//	*ChangesetChunk_Object
	Chunk         isChangesetChunk_Chunk `protobuf_oneof:"chunk"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangesetChunk) Reset() {
	*x = ChangesetChunk{}
	mi := &file_slice_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesetChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesetChunk) ProtoMessage() {}

func (x *ChangesetChunk) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesetChunk.ProtoReflect.Descriptor instead.
func (*ChangesetChunk) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{8}
}

func (x *ChangesetChunk) GetChunk() isChangesetChunk_Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChangesetChunk) GetMetadata() *ChangesetMetadata {
	if x != nil {
		if x, ok := x.Chunk.(*ChangesetChunk_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ChangesetChunk) GetObject() *Object {
	if x != nil {
		if x, ok := x.Chunk.(*ChangesetChunk_Object); ok {
			return x.Object
		}
	}
	return nil
}

type isChangesetChunk_Chunk interface {
	isChangesetChunk_Chunk()
}

type ChangesetChunk_Metadata struct {
	Metadata *ChangesetMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type ChangesetChunk_Object struct {
	Object *Object `protobuf:"bytes,2,opt,name=object,proto3,oneof"`
}

func (*ChangesetChunk_Metadata) isChangesetChunk_Chunk() {}

func (*ChangesetChunk_Object) isChangesetChunk_Chunk() {}

type ChangesetMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SliceId        string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	BaseCommitHash string                 `protobuf:"bytes,2,opt,name=base_commit_hash,json=baseCommitHash,proto3" json:"base_commit_hash,omitempty"`
	Author         string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangesetMetadata) Reset() {
	*x = ChangesetMetadata{}
	mi := &file_slice_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesetMetadata) ProtoMessage() {}

func (x *ChangesetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesetMetadata.ProtoReflect.Descriptor instead.
func (*ChangesetMetadata) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{9}
}

func (x *ChangesetMetadata) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ChangesetMetadata) GetBaseCommitHash() string {
	if x != nil {
		return x.BaseCommitHash
	}
	return ""
}

func (x *ChangesetMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChangesetMetadata) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Object struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ObjectType             `protobuf:"varint,1,opt,name=type,proto3,enum=slice.v1.ObjectType" json:"type,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_slice_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{10}
}

func (x *Object) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_BLOB
}

func (x *Object) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Object) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReviewChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewChangesetRequest) Reset() {
	*x = ReviewChangesetRequest{}
	mi := &file_slice_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewChangesetRequest) ProtoMessage() {}

func (x *ReviewChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewChangesetRequest.ProtoReflect.Descriptor instead.
func (*ReviewChangesetRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{11}
}

func (x *ReviewChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

type ReviewChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changeset     *ChangesetInfo         `protobuf:"bytes,1,opt,name=changeset,proto3" json:"changeset,omitempty"`
	Diff          *DiffSummary           `protobuf:"bytes,2,opt,name=diff,proto3" json:"diff,omitempty"`
	ReviewStatus  ReviewStatus           `protobuf:"varint,3,opt,name=review_status,json=reviewStatus,proto3,enum=slice.v1.ReviewStatus" json:"review_status,omitempty"`
	Warnings      []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewChangesetResponse) Reset() {
	*x = ReviewChangesetResponse{}
	mi := &file_slice_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewChangesetResponse) ProtoMessage() {}

func (x *ReviewChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewChangesetResponse.ProtoReflect.Descriptor instead.
func (*ReviewChangesetResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{12}
}

func (x *ReviewChangesetResponse) GetChangeset() *ChangesetInfo {
	if x != nil {
		return x.Changeset
	}
	return nil
}

func (x *ReviewChangesetResponse) GetDiff() *DiffSummary {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *ReviewChangesetResponse) GetReviewStatus() ReviewStatus {
	if x != nil {
		return x.ReviewStatus
	}
	return ReviewStatus_READY_FOR_MERGE
}

func (x *ReviewChangesetResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type DiffSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilesAdded    int32                  `protobuf:"varint,1,opt,name=files_added,json=filesAdded,proto3" json:"files_added,omitempty"`
	FilesModified int32                  `protobuf:"varint,2,opt,name=files_modified,json=filesModified,proto3" json:"files_modified,omitempty"`
	FilesDeleted  int32                  `protobuf:"varint,3,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	LinesAdded    int64                  `protobuf:"varint,4,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`
	LinesRemoved  int64                  `protobuf:"varint,5,opt,name=lines_removed,json=linesRemoved,proto3" json:"lines_removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffSummary) Reset() {
	*x = DiffSummary{}
	mi := &file_slice_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffSummary) ProtoMessage() {}

func (x *DiffSummary) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffSummary.ProtoReflect.Descriptor instead.
func (*DiffSummary) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{13}
}

func (x *DiffSummary) GetFilesAdded() int32 {
	if x != nil {
		return x.FilesAdded
	}
	return 0
}

func (x *DiffSummary) GetFilesModified() int32 {
	if x != nil {
		return x.FilesModified
	}
	return 0
}

func (x *DiffSummary) GetFilesDeleted() int32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *DiffSummary) GetLinesAdded() int64 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *DiffSummary) GetLinesRemoved() int64 {
	if x != nil {
		return x.LinesRemoved
	}
	return 0
}

type MergeChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChangesetRequest) Reset() {
	*x = MergeChangesetRequest{}
	mi := &file_slice_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChangesetRequest) ProtoMessage() {}

func (x *MergeChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChangesetRequest.ProtoReflect.Descriptor instead.
func (*MergeChangesetRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{14}
}

func (x *MergeChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

type MergeChangesetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        MergeStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=slice.v1.MergeStatus" json:"status,omitempty"`
	NewCommitHash string                 `protobuf:"bytes,2,opt,name=new_commit_hash,json=newCommitHash,proto3" json:"new_commit_hash,omitempty"`
	ChangesetId   string                 `protobuf:"bytes,3,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeChangesetResponse) Reset() {
	*x = MergeChangesetResponse{}
	mi := &file_slice_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeChangesetResponse) ProtoMessage() {}

func (x *MergeChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeChangesetResponse.ProtoReflect.Descriptor instead.
func (*MergeChangesetResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{15}
}

func (x *MergeChangesetResponse) GetStatus() MergeStatus {
	if x != nil {
		return x.Status
	}
	return MergeStatus_MERGE_STATUS_SUCCESS
}

func (x *MergeChangesetResponse) GetNewCommitHash() string {
	if x != nil {
		return x.NewCommitHash
	}
	return ""
}

func (x *MergeChangesetResponse) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *MergeChangesetResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type Conflict struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FileId              string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ConflictingSliceIds []string               `protobuf:"bytes,2,rep,name=conflicting_slice_ids,json=conflictingSliceIds,proto3" json:"conflicting_slice_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_slice_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{16}
}

func (x *Conflict) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Conflict) GetConflictingSliceIds() []string {
	if x != nil {
		return x.ConflictingSliceIds
	}
	return nil
}

type RebaseChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RebaseChangesetRequest) Reset() {
	*x = RebaseChangesetRequest{}
	mi := &file_slice_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseChangesetRequest) ProtoMessage() {}

func (x *RebaseChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseChangesetRequest.ProtoReflect.Descriptor instead.
func (*RebaseChangesetRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{17}
}

func (x *RebaseChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

type RebaseChangesetResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              RebaseStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=slice.v1.RebaseStatus" json:"status,omitempty"`
	NewBaseCommitHash   string                 `protobuf:"bytes,2,opt,name=new_base_commit_hash,json=newBaseCommitHash,proto3" json:"new_base_commit_hash,omitempty"`
	SliceCommitsToApply []string               `protobuf:"bytes,3,rep,name=slice_commits_to_apply,json=sliceCommitsToApply,proto3" json:"slice_commits_to_apply,omitempty"`
	Conflicts           []*Conflict            `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RebaseChangesetResponse) Reset() {
	*x = RebaseChangesetResponse{}
	mi := &file_slice_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RebaseChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RebaseChangesetResponse) ProtoMessage() {}

func (x *RebaseChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RebaseChangesetResponse.ProtoReflect.Descriptor instead.
func (*RebaseChangesetResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{18}
}

func (x *RebaseChangesetResponse) GetStatus() RebaseStatus {
	if x != nil {
		return x.Status
	}
	return RebaseStatus_REBASE_STATUS_SUCCESS
}

func (x *RebaseChangesetResponse) GetNewBaseCommitHash() string {
	if x != nil {
		return x.NewBaseCommitHash
	}
	return ""
}

func (x *RebaseChangesetResponse) GetSliceCommitsToApply() []string {
	if x != nil {
		return x.SliceCommitsToApply
	}
	return nil
}

func (x *RebaseChangesetResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type ListChangesetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	StatusFilter  ChangesetStatus        `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=slice.v1.ChangesetStatus" json:"status_filter,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesetsRequest) Reset() {
	*x = ListChangesetsRequest{}
	mi := &file_slice_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesetsRequest) ProtoMessage() {}

func (x *ListChangesetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesetsRequest.ProtoReflect.Descriptor instead.
func (*ListChangesetsRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListChangesetsRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ListChangesetsRequest) GetStatusFilter() ChangesetStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ChangesetStatus_PENDING
}

func (x *ListChangesetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChangesetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changesets    []*ChangesetInfo       `protobuf:"bytes,1,rep,name=changesets,proto3" json:"changesets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesetsResponse) Reset() {
	*x = ListChangesetsResponse{}
	mi := &file_slice_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesetsResponse) ProtoMessage() {}

func (x *ListChangesetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesetsResponse.ProtoReflect.Descriptor instead.
func (*ListChangesetsResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListChangesetsResponse) GetChangesets() []*ChangesetInfo {
	if x != nil {
		return x.Changesets
	}
	return nil
}

type ChangesetInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId    string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	ChangesetHash  string                 `protobuf:"bytes,2,opt,name=changeset_hash,json=changesetHash,proto3" json:"changeset_hash,omitempty"`
	SliceId        string                 `protobuf:"bytes,3,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	BaseCommitHash string                 `protobuf:"bytes,4,opt,name=base_commit_hash,json=baseCommitHash,proto3" json:"base_commit_hash,omitempty"`
	ModifiedFiles  []string               `protobuf:"bytes,5,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`
	Status         ChangesetStatus        `protobuf:"varint,6,opt,name=status,proto3,enum=slice.v1.ChangesetStatus" json:"status,omitempty"`
	Author         string                 `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MergedAt       int64                  `protobuf:"varint,9,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
	Message        string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangesetInfo) Reset() {
	*x = ChangesetInfo{}
	mi := &file_slice_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesetInfo) ProtoMessage() {}

func (x *ChangesetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesetInfo.ProtoReflect.Descriptor instead.
func (*ChangesetInfo) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{21}
}

func (x *ChangesetInfo) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *ChangesetInfo) GetChangesetHash() string {
	if x != nil {
		return x.ChangesetHash
	}
	return ""
}

func (x *ChangesetInfo) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ChangesetInfo) GetBaseCommitHash() string {
	if x != nil {
		return x.BaseCommitHash
	}
	return ""
}

func (x *ChangesetInfo) GetModifiedFiles() []string {
	if x != nil {
		return x.ModifiedFiles
	}
	return nil
}

func (x *ChangesetInfo) GetStatus() ChangesetStatus {
	if x != nil {
		return x.Status
	}
	return ChangesetStatus_PENDING
}

func (x *ChangesetInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChangesetInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChangesetInfo) GetMergedAt() int64 {
	if x != nil {
		return x.MergedAt
	}
	return 0
}

func (x *ChangesetInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommitHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SliceId        string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Limit          int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FromCommitHash string                 `protobuf:"bytes,3,opt,name=from_commit_hash,json=fromCommitHash,proto3" json:"from_commit_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitHistoryRequest) Reset() {
	*x = CommitHistoryRequest{}
	mi := &file_slice_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitHistoryRequest) ProtoMessage() {}

func (x *CommitHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitHistoryRequest.ProtoReflect.Descriptor instead.
func (*CommitHistoryRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{22}
}

func (x *CommitHistoryRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CommitHistoryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CommitHistoryRequest) GetFromCommitHash() string {
	if x != nil {
		return x.FromCommitHash
	}
	return ""
}

type CommitHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commits       []*CommitInfo          `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitHistoryResponse) Reset() {
	*x = CommitHistoryResponse{}
	mi := &file_slice_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitHistoryResponse) ProtoMessage() {}

func (x *CommitHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitHistoryResponse.ProtoReflect.Descriptor instead.
func (*CommitHistoryResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{23}
}

func (x *CommitHistoryResponse) GetCommits() []*CommitInfo {
	if x != nil {
		return x.Commits
	}
	return nil
}

type CommitInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ParentHash    string                 `protobuf:"bytes,3,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitInfo) Reset() {
	*x = CommitInfo{}
	mi := &file_slice_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitInfo) ProtoMessage() {}

func (x *CommitInfo) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitInfo.ProtoReflect.Descriptor instead.
func (*CommitInfo) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{24}
}

func (x *CommitInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *CommitInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CommitInfo) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *CommitInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_slice_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{25}
}

func (x *StateRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type StateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LatestCommitHash string                 `protobuf:"bytes,1,opt,name=latest_commit_hash,json=latestCommitHash,proto3" json:"latest_commit_hash,omitempty"`
	ModifiedFiles    []string               `protobuf:"bytes,2,rep,name=modified_files,json=modifiedFiles,proto3" json:"modified_files,omitempty"`
	LastModified     int64                  `protobuf:"varint,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_slice_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_slice_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_slice_service_proto_rawDescGZIP(), []int{26}
}

func (x *StateResponse) GetLatestCommitHash() string {
	if x != nil {
		return x.LatestCommitHash
	}
	return ""
}

func (x *StateResponse) GetModifiedFiles() []string {
	if x != nil {
		return x.ModifiedFiles
	}
	return nil
}

func (x *StateResponse) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

var File_slice_service_proto protoreflect.FileDescriptor

const file_slice_service_proto_rawDesc = "" +
	"\n" +
	"\x13slice_service.proto\x12\bslice.v1\"M\n" +
	"\x0fCheckoutRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x1f\n" +
	"\vcommit_hash\x18\x02 \x01(\tR\n" +
	"commitHash\"t\n" +
	"\x10CheckoutResponse\x123\n" +
	"\bmanifest\x18\x01 \x01(\v2\x17.slice.v1.SliceManifestR\bmanifest\x12+\n" +
	"\x05files\x18\x02 \x03(\v2\x15.slice.v1.FileContentR\x05files\"m\n" +
	"\rSliceManifest\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12;\n" +
	"\rfile_metadata\x18\x02 \x03(\v2\x16.slice.v1.FileMetadataR\ffileMetadata\"\x84\x01\n" +
	"\fFileMetadata\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x1f\n" +
	"\vcontent_url\x18\x05 \x01(\tR\n" +
	"contentUrl\"@\n" +
	"\vFileContent\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"|\n" +
	"\rCheckoutChunk\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x17.slice.v1.SliceManifestH\x00R\bmanifest\x12+\n" +
	"\x04file\x18\x02 \x01(\v2\x15.slice.v1.FileContentH\x00R\x04fileB\a\n" +
	"\x05chunk\"\xe2\x01\n" +
	"\x16CreateChangesetRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12(\n" +
	"\x10base_commit_hash\x18\x02 \x01(\tR\x0ebaseCommitHash\x12*\n" +
	"\aobjects\x18\x03 \x03(\v2\x10.slice.v1.ObjectR\aobjects\x12%\n" +
	"\x0emodified_files\x18\x04 \x03(\tR\rmodifiedFiles\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x96\x01\n" +
	"\x17CreateChangesetResponse\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12%\n" +
	"\x0echangeset_hash\x18\x02 \x01(\tR\rchangesetHash\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.slice.v1.ChangesetStatusR\x06status\"\x80\x01\n" +
	"\x0eChangesetChunk\x129\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.slice.v1.ChangesetMetadataH\x00R\bmetadata\x12*\n" +
	"\x06object\x18\x02 \x01(\v2\x10.slice.v1.ObjectH\x00R\x06objectB\a\n" +
	"\x05chunk\"\x8a\x01\n" +
	"\x11ChangesetMetadata\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12(\n" +
	"\x10base_commit_hash\x18\x02 \x01(\tR\x0ebaseCommitHash\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"Z\n" +
	"\x06Object\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.slice.v1.ObjectTypeR\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\";\n" +
	"\x16ReviewChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\"\xd4\x01\n" +
	"\x17ReviewChangesetResponse\x125\n" +
	"\tchangeset\x18\x01 \x01(\v2\x17.slice.v1.ChangesetInfoR\tchangeset\x12)\n" +
	"\x04diff\x18\x02 \x01(\v2\x15.slice.v1.DiffSummaryR\x04diff\x12;\n" +
	"\rreview_status\x18\x03 \x01(\x0e2\x16.slice.v1.ReviewStatusR\freviewStatus\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"\xc0\x01\n" +
	"\vDiffSummary\x12\x1f\n" +
	"\vfiles_added\x18\x01 \x01(\x05R\n" +
	"filesAdded\x12%\n" +
	"\x0efiles_modified\x18\x02 \x01(\x05R\rfilesModified\x12#\n" +
	"\rfiles_deleted\x18\x03 \x01(\x05R\ffilesDeleted\x12\x1f\n" +
	"\vlines_added\x18\x04 \x01(\x03R\n" +
	"linesAdded\x12#\n" +
	"\rlines_removed\x18\x05 \x01(\x03R\flinesRemoved\":\n" +
	"\x15MergeChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\"\xc4\x01\n" +
	"\x16MergeChangesetResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.slice.v1.MergeStatusR\x06status\x12&\n" +
	"\x0fnew_commit_hash\x18\x02 \x01(\tR\rnewCommitHash\x12!\n" +
	"\fchangeset_id\x18\x03 \x01(\tR\vchangesetId\x120\n" +
	"\tconflicts\x18\x04 \x03(\v2\x12.slice.v1.ConflictR\tconflicts\"W\n" +
	"\bConflict\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x122\n" +
	"\x15conflicting_slice_ids\x18\x02 \x03(\tR\x13conflictingSliceIds\";\n" +
	"\x16RebaseChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\"\xe1\x01\n" +
	"\x17RebaseChangesetResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.slice.v1.RebaseStatusR\x06status\x12/\n" +
	"\x14new_base_commit_hash\x18\x02 \x01(\tR\x11newBaseCommitHash\x123\n" +
	"\x16slice_commits_to_apply\x18\x03 \x03(\tR\x13sliceCommitsToApply\x120\n" +
	"\tconflicts\x18\x04 \x03(\v2\x12.slice.v1.ConflictR\tconflicts\"\x88\x01\n" +
	"\x15ListChangesetsRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12>\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2\x19.slice.v1.ChangesetStatusR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Q\n" +
	"\x16ListChangesetsResponse\x127\n" +
	"\n" +
	"changesets\x18\x01 \x03(\v2\x17.slice.v1.ChangesetInfoR\n" +
	"changesets\"\xe6\x02\n" +
	"\rChangesetInfo\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12%\n" +
	"\x0echangeset_hash\x18\x02 \x01(\tR\rchangesetHash\x12\x19\n" +
	"\bslice_id\x18\x03 \x01(\tR\asliceId\x12(\n" +
	"\x10base_commit_hash\x18\x04 \x01(\tR\x0ebaseCommitHash\x12%\n" +
	"\x0emodified_files\x18\x05 \x03(\tR\rmodifiedFiles\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.slice.v1.ChangesetStatusR\x06status\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1b\n" +
	"\tmerged_at\x18\t \x01(\x03R\bmergedAt\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"q\n" +
	"\x14CommitHistoryRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12(\n" +
	"\x10from_commit_hash\x18\x03 \x01(\tR\x0efromCommitHash\"G\n" +
	"\x15CommitHistoryResponse\x12.\n" +
	"\acommits\x18\x01 \x03(\v2\x14.slice.v1.CommitInfoR\acommits\"\x86\x01\n" +
	"\n" +
	"CommitInfo\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vparent_hash\x18\x03 \x01(\tR\n" +
	"parentHash\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\")\n" +
	"\fStateRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"\x89\x01\n" +
	"\rStateResponse\x12,\n" +
	"\x12latest_commit_hash\x18\x01 \x01(\tR\x10latestCommitHash\x12%\n" +
	"\x0emodified_files\x18\x02 \x03(\tR\rmodifiedFiles\x12#\n" +
	"\rlast_modified\x18\x03 \x01(\x03R\flastModified*J\n" +
	"\n" +
	"ObjectType\x12\b\n" +
	"\x04BLOB\x10\x00\x12\b\n" +
	"\x04TREE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\r\n" +
	"\tSLICE_DEF\x10\x03\x12\r\n" +
	"\tCHANGESET\x10\x04*Z\n" +
	"\vMergeStatus\x12\x18\n" +
	"\x14MERGE_STATUS_SUCCESS\x10\x00\x12\x19\n" +
	"\x15MERGE_STATUS_CONFLICT\x10\x01\x12\x16\n" +
	"\x12MERGE_STATUS_ERROR\x10\x02*}\n" +
	"\fRebaseStatus\x12\x19\n" +
	"\x15REBASE_STATUS_SUCCESS\x10\x00\x12\x1a\n" +
	"\x16REBASE_STATUS_CONFLICT\x10\x01\x12\x1d\n" +
	"\x19REBASE_STATUS_NEEDS_MERGE\x10\x02\x12\x17\n" +
	"\x13REBASE_STATUS_ERROR\x10\x03*F\n" +
	"\x0fChangesetStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\f\n" +
	"\bAPPROVED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02\x12\n" +
	"\n" +
	"\x06MERGED\x10\x03*H\n" +
	"\fReviewStatus\x12\x13\n" +
	"\x0fREADY_FOR_MERGE\x10\x00\x12\x10\n" +
	"\fNEEDS_REBASE\x10\x01\x12\x11\n" +
	"\rHAS_CONFLICTS\x10\x022\xc3\x06\n" +
	"\fSliceService\x12F\n" +
	"\rCheckoutSlice\x12\x19.slice.v1.CheckoutRequest\x1a\x1a.slice.v1.CheckoutResponse\x12V\n" +
	"\x0fCreateChangeset\x12 .slice.v1.CreateChangesetRequest\x1a!.slice.v1.CreateChangesetResponse\x12V\n" +
	"\x0fReviewChangeset\x12 .slice.v1.ReviewChangesetRequest\x1a!.slice.v1.ReviewChangesetResponse\x12S\n" +
	"\x0eMergeChangeset\x12\x1f.slice.v1.MergeChangesetRequest\x1a .slice.v1.MergeChangesetResponse\x12V\n" +
	"\x0fRebaseChangeset\x12 .slice.v1.RebaseChangesetRequest\x1a!.slice.v1.RebaseChangesetResponse\x12R\n" +
	"\x0fGetSliceCommits\x12\x1e.slice.v1.CommitHistoryRequest\x1a\x1f.slice.v1.CommitHistoryResponse\x12@\n" +
	"\rGetSliceState\x12\x16.slice.v1.StateRequest\x1a\x17.slice.v1.StateResponse\x12S\n" +
	"\x0eListChangesets\x12\x1f.slice.v1.ListChangesetsRequest\x1a .slice.v1.ListChangesetsResponse\x12K\n" +
	"\x13StreamCheckoutSlice\x12\x19.slice.v1.CheckoutRequest\x1a\x17.slice.v1.CheckoutChunk0\x01\x12V\n" +
	"\x15StreamCreateChangeset\x12\x18.slice.v1.ChangesetChunk\x1a!.slice.v1.CreateChangesetResponse(\x01B)Z'github.com/niczy/gitslice/proto;slicev1b\x06proto3"

var (
	file_slice_service_proto_rawDescOnce sync.Once
	file_slice_service_proto_rawDescData []byte
)

func file_slice_service_proto_rawDescGZIP() []byte {
	file_slice_service_proto_rawDescOnce.Do(func() {
		file_slice_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_slice_service_proto_rawDesc), len(file_slice_service_proto_rawDesc)))
	})
	return file_slice_service_proto_rawDescData
}

var file_slice_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_slice_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_slice_service_proto_goTypes = []any{
	(ObjectType)(0),                 // 0: slice.v1.ObjectType
	(MergeStatus)(0),                // 1: slice.v1.MergeStatus
	(RebaseStatus)(0),               // 2: slice.v1.RebaseStatus
	(ChangesetStatus)(0),            // 3: slice.v1.ChangesetStatus
	(ReviewStatus)(0),               // 4: slice.v1.ReviewStatus
	(*CheckoutRequest)(nil),         // 5: slice.v1.CheckoutRequest
	(*CheckoutResponse)(nil),        // 6: slice.v1.CheckoutResponse
	(*SliceManifest)(nil),           // 7: slice.v1.SliceManifest
	(*FileMetadata)(nil),            // 8: slice.v1.FileMetadata
	(*FileContent)(nil),             // 9: slice.v1.FileContent
	(*CheckoutChunk)(nil),           // 10: slice.v1.CheckoutChunk
	(*CreateChangesetRequest)(nil),  // 11: slice.v1.CreateChangesetRequest
	(*CreateChangesetResponse)(nil), // 12: slice.v1.CreateChangesetResponse
	(*ChangesetChunk)(nil),          // 13: slice.v1.ChangesetChunk
	(*ChangesetMetadata)(nil),       // 14: slice.v1.ChangesetMetadata
	(*Object)(nil),                  // 15: slice.v1.Object
	(*ReviewChangesetRequest)(nil),  // 16: slice.v1.ReviewChangesetRequest
	(*ReviewChangesetResponse)(nil), // 17: slice.v1.ReviewChangesetResponse
	(*DiffSummary)(nil),             // 18: slice.v1.DiffSummary
	(*MergeChangesetRequest)(nil),   // 19: slice.v1.MergeChangesetRequest
	(*MergeChangesetResponse)(nil),  // 20: slice.v1.MergeChangesetResponse
	(*Conflict)(nil),                // 21: slice.v1.Conflict
	(*RebaseChangesetRequest)(nil),  // 22: slice.v1.RebaseChangesetRequest
	(*RebaseChangesetResponse)(nil), // 23: slice.v1.RebaseChangesetResponse
	(*ListChangesetsRequest)(nil),   // 24: slice.v1.ListChangesetsRequest
	(*ListChangesetsResponse)(nil),  // 25: slice.v1.ListChangesetsResponse
	(*ChangesetInfo)(nil),           // 26: slice.v1.ChangesetInfo
	(*CommitHistoryRequest)(nil),    // 27: slice.v1.CommitHistoryRequest
	(*CommitHistoryResponse)(nil),   // 28: slice.v1.CommitHistoryResponse
	(*CommitInfo)(nil),              // 29: slice.v1.CommitInfo
	(*StateRequest)(nil),            // 30: slice.v1.StateRequest
	(*StateResponse)(nil),           // 31: slice.v1.StateResponse
}
var file_slice_service_proto_depIdxs = []int32{
	7,  // 0: slice.v1.CheckoutResponse.manifest:type_name -> slice.v1.SliceManifest
	9,  // 1: slice.v1.CheckoutResponse.files:type_name -> slice.v1.FileContent
	8,  // 2: slice.v1.SliceManifest.file_metadata:type_name -> slice.v1.FileMetadata
	7,  // 3: slice.v1.CheckoutChunk.manifest:type_name -> slice.v1.SliceManifest
	9,  // 4: slice.v1.CheckoutChunk.file:type_name -> slice.v1.FileContent
	15, // 5: slice.v1.CreateChangesetRequest.objects:type_name -> slice.v1.Object
	3,  // 6: slice.v1.CreateChangesetResponse.status:type_name -> slice.v1.ChangesetStatus
	14, // 7: slice.v1.ChangesetChunk.metadata:type_name -> slice.v1.ChangesetMetadata
	15, // 8: slice.v1.ChangesetChunk.object:type_name -> slice.v1.Object
	0,  // 9: slice.v1.Object.type:type_name -> slice.v1.ObjectType
	26, // 10: slice.v1.ReviewChangesetResponse.changeset:type_name -> slice.v1.ChangesetInfo
	18, // 11: slice.v1.ReviewChangesetResponse.diff:type_name -> slice.v1.DiffSummary
	4,  // 12: slice.v1.ReviewChangesetResponse.review_status:type_name -> slice.v1.ReviewStatus
	1,  // 13: slice.v1.MergeChangesetResponse.status:type_name -> slice.v1.MergeStatus
	21, // 14: slice.v1.MergeChangesetResponse.conflicts:type_name -> slice.v1.Conflict
	2,  // 15: slice.v1.RebaseChangesetResponse.status:type_name -> slice.v1.RebaseStatus
	21, // 16: slice.v1.RebaseChangesetResponse.conflicts:type_name -> slice.v1.Conflict
	3,  // 17: slice.v1.ListChangesetsRequest.status_filter:type_name -> slice.v1.ChangesetStatus
	26, // 18: slice.v1.ListChangesetsResponse.changesets:type_name -> slice.v1.ChangesetInfo
	3,  // 19: slice.v1.ChangesetInfo.status:type_name -> slice.v1.ChangesetStatus
	29, // 20: slice.v1.CommitHistoryResponse.commits:type_name -> slice.v1.CommitInfo
	5,  // 21: slice.v1.SliceService.CheckoutSlice:input_type -> slice.v1.CheckoutRequest
	11, // 22: slice.v1.SliceService.CreateChangeset:input_type -> slice.v1.CreateChangesetRequest
	16, // 23: slice.v1.SliceService.ReviewChangeset:input_type -> slice.v1.ReviewChangesetRequest
	19, // 24: slice.v1.SliceService.MergeChangeset:input_type -> slice.v1.MergeChangesetRequest
	22, // 25: slice.v1.SliceService.RebaseChangeset:input_type -> slice.v1.RebaseChangesetRequest
	27, // 26: slice.v1.SliceService.GetSliceCommits:input_type -> slice.v1.CommitHistoryRequest
	30, // 27: slice.v1.SliceService.GetSliceState:input_type -> slice.v1.StateRequest
	24, // 28: slice.v1.SliceService.ListChangesets:input_type -> slice.v1.ListChangesetsRequest
	5,  // 29: slice.v1.SliceService.StreamCheckoutSlice:input_type -> slice.v1.CheckoutRequest
	13, // 30: slice.v1.SliceService.StreamCreateChangeset:input_type -> slice.v1.ChangesetChunk
	6,  // 31: slice.v1.SliceService.CheckoutSlice:output_type -> slice.v1.CheckoutResponse
	12, // 32: slice.v1.SliceService.CreateChangeset:output_type -> slice.v1.CreateChangesetResponse
	17, // 33: slice.v1.SliceService.ReviewChangeset:output_type -> slice.v1.ReviewChangesetResponse
	20, // 34: slice.v1.SliceService.MergeChangeset:output_type -> slice.v1.MergeChangesetResponse
	23, // 35: slice.v1.SliceService.RebaseChangeset:output_type -> slice.v1.RebaseChangesetResponse
	28, // 36: slice.v1.SliceService.GetSliceCommits:output_type -> slice.v1.CommitHistoryResponse
	31, // 37: slice.v1.SliceService.GetSliceState:output_type -> slice.v1.StateResponse
	25, // 38: slice.v1.SliceService.ListChangesets:output_type -> slice.v1.ListChangesetsResponse
	10, // 39: slice.v1.SliceService.StreamCheckoutSlice:output_type -> slice.v1.CheckoutChunk
	12, // 40: slice.v1.SliceService.StreamCreateChangeset:output_type -> slice.v1.CreateChangesetResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_slice_service_proto_init() }
func file_slice_service_proto_init() {
	if File_slice_service_proto != nil {
		return
	}
	file_slice_service_proto_msgTypes[5].OneofWrappers = []any{
		(*CheckoutChunk_Manifest)(nil),
		(*CheckoutChunk_File)(nil),
	}
	file_slice_service_proto_msgTypes[8].OneofWrappers = []any{
		(*ChangesetChunk_Metadata)(nil),
		(*ChangesetChunk_Object)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_slice_service_proto_rawDesc), len(file_slice_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_slice_service_proto_goTypes,
		DependencyIndexes: file_slice_service_proto_depIdxs,
		EnumInfos:         file_slice_service_proto_enumTypes,
		MessageInfos:      file_slice_service_proto_msgTypes,
	}.Build()
	File_slice_service_proto = out.File
	file_slice_service_proto_goTypes = nil
	file_slice_service_proto_depIdxs = nil
}
