load("@rules_go//proto:def.bzl", "go_proto_library")

proto_library(
    name = "file_proto",
    srcs = ["file_service.proto"],
    deps = ["//proto/google/api:annotations_proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "file",
    compilers = [
        "@rules_go//proto:go_grpc",
        "//:grpc_gateway_compiler",
    ],
    importpath = "github.com/niczy/gitslice/proto/file",
    proto = ":file_proto",
    deps = [
        "@org_golang_google_genproto_googleapis_api//annotations",
    ],
    visibility = ["//visibility:public"],
)
