// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: file_service.proto

package filev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_ENTRY_TYPE_FILE        EntryType = 1
	EntryType_ENTRY_TYPE_DIRECTORY   EntryType = 2
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_FILE",
		2: "ENTRY_TYPE_DIRECTORY",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_FILE":        1,
		"ENTRY_TYPE_DIRECTORY":   2,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_service_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_file_service_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{0}
}

// ChangeType represents the type of change made to a file
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 0
	ChangeType_CHANGE_TYPE_ADD         ChangeType = 1
	ChangeType_CHANGE_TYPE_MODIFY      ChangeType = 2
	ChangeType_CHANGE_TYPE_DELETE      ChangeType = 3
	ChangeType_CHANGE_TYPE_RENAME      ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNSPECIFIED",
		1: "CHANGE_TYPE_ADD",
		2: "CHANGE_TYPE_MODIFY",
		3: "CHANGE_TYPE_DELETE",
		4: "CHANGE_TYPE_RENAME",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNSPECIFIED": 0,
		"CHANGE_TYPE_ADD":         1,
		"CHANGE_TYPE_MODIFY":      2,
		"CHANGE_TYPE_DELETE":      3,
		"CHANGE_TYPE_RENAME":      4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_file_service_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_file_service_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{1}
}

// SliceVersion specifies a slice at a particular version
type SliceVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`       // Required: which slice
	SliceHash     string                 `protobuf:"bytes,2,opt,name=slice_hash,json=sliceHash,proto3" json:"slice_hash,omitempty"` // Optional: commit hash (default: HEAD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceVersion) Reset() {
	*x = SliceVersion{}
	mi := &file_file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceVersion) ProtoMessage() {}

func (x *SliceVersion) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceVersion.ProtoReflect.Descriptor instead.
func (*SliceVersion) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{0}
}

func (x *SliceVersion) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *SliceVersion) GetSliceHash() string {
	if x != nil {
		return x.SliceHash
	}
	return ""
}

type ListEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Primary param (directory path)
	Limit int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Version specifier (optional, mutually exclusive)
	//
	// Types that are valid to be assigned to Version:
	//
	//	*ListEntriesRequest_CommitHash
	//	*ListEntriesRequest_SliceVersion
	Version       isListEntriesRequest_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListEntriesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetVersion() isListEntriesRequest_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ListEntriesRequest) GetCommitHash() string {
	if x != nil {
		if x, ok := x.Version.(*ListEntriesRequest_CommitHash); ok {
			return x.CommitHash
		}
	}
	return ""
}

func (x *ListEntriesRequest) GetSliceVersion() *SliceVersion {
	if x != nil {
		if x, ok := x.Version.(*ListEntriesRequest_SliceVersion); ok {
			return x.SliceVersion
		}
	}
	return nil
}

type isListEntriesRequest_Version interface {
	isListEntriesRequest_Version()
}

type ListEntriesRequest_CommitHash struct {
	CommitHash string `protobuf:"bytes,10,opt,name=commit_hash,json=commitHash,proto3,oneof"` // Global commit hash (uses root_slice)
}

type ListEntriesRequest_SliceVersion struct {
	SliceVersion *SliceVersion `protobuf:"bytes,11,opt,name=slice_version,json=sliceVersion,proto3,oneof"` // Specific slice at version
}

func (*ListEntriesRequest_CommitHash) isListEntriesRequest_Version() {}

func (*ListEntriesRequest_SliceVersion) isListEntriesRequest_Version() {}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*DirectoryEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Truncated     bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListEntriesResponse) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ListEntriesResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListEntriesResponse) GetEntries() []*DirectoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type DirectoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          EntryType              `protobuf:"varint,3,opt,name=type,proto3,enum=file.v1.EntryType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	HasChildren   bool                   `protobuf:"varint,5,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryEntry) Reset() {
	*x = DirectoryEntry{}
	mi := &file_file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryEntry) ProtoMessage() {}

func (x *DirectoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryEntry.ProtoReflect.Descriptor instead.
func (*DirectoryEntry) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{3}
}

func (x *DirectoryEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirectoryEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryEntry) GetType() EntryType {
	if x != nil {
		return x.Type
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *DirectoryEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirectoryEntry) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

type GetFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // Required: file path
	// Version specifier (optional, mutually exclusive)
	//
	// Types that are valid to be assigned to Version:
	//
	//	*GetFileRequest_CommitHash
	//	*GetFileRequest_SliceVersion
	Version       isGetFileRequest_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileRequest) GetVersion() isGetFileRequest_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetFileRequest) GetCommitHash() string {
	if x != nil {
		if x, ok := x.Version.(*GetFileRequest_CommitHash); ok {
			return x.CommitHash
		}
	}
	return ""
}

func (x *GetFileRequest) GetSliceVersion() *SliceVersion {
	if x != nil {
		if x, ok := x.Version.(*GetFileRequest_SliceVersion); ok {
			return x.SliceVersion
		}
	}
	return nil
}

type isGetFileRequest_Version interface {
	isGetFileRequest_Version()
}

type GetFileRequest_CommitHash struct {
	CommitHash string `protobuf:"bytes,10,opt,name=commit_hash,json=commitHash,proto3,oneof"` // Global commit hash (uses root_slice)
}

type GetFileRequest_SliceVersion struct {
	SliceVersion *SliceVersion `protobuf:"bytes,11,opt,name=slice_version,json=sliceVersion,proto3,oneof"` // Specific slice at version
}

func (*GetFileRequest_CommitHash) isGetFileRequest_Version() {}

func (*GetFileRequest_SliceVersion) isGetFileRequest_Version() {}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{6}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// FileChangeRecord represents a single change to a file within a commit
type FileChangeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                            // Unique identifier for this change
	SliceId       string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`                                   // Which slice this change belongs to
	CommitHash    string                 `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`                          // Commit that made this change
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`                                                        // File path (after change, for renames)
	OldPath       string                 `protobuf:"bytes,5,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`                                   // Previous path (only for renames)
	ChangeType    ChangeType             `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=file.v1.ChangeType" json:"change_type,omitempty"` // Type of change
	OldHash       string                 `protobuf:"bytes,7,opt,name=old_hash,json=oldHash,proto3" json:"old_hash,omitempty"`                                   // Content hash before change (empty for add)
	NewHash       string                 `protobuf:"bytes,8,opt,name=new_hash,json=newHash,proto3" json:"new_hash,omitempty"`                                   // Content hash after change (empty for delete)
	LinesAdded    int32                  `protobuf:"varint,9,opt,name=lines_added,json=linesAdded,proto3" json:"lines_added,omitempty"`                         // Number of lines added
	LinesDeleted  int32                  `protobuf:"varint,10,opt,name=lines_deleted,json=linesDeleted,proto3" json:"lines_deleted,omitempty"`                  // Number of lines removed
	Author        string                 `protobuf:"bytes,11,opt,name=author,proto3" json:"author,omitempty"`                                                   // Who made this change
	Message       string                 `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`                                                 // Commit message
	Timestamp     int64                  `protobuf:"varint,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                            // Unix timestamp of the change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChangeRecord) Reset() {
	*x = FileChangeRecord{}
	mi := &file_file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChangeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChangeRecord) ProtoMessage() {}

func (x *FileChangeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChangeRecord.ProtoReflect.Descriptor instead.
func (*FileChangeRecord) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{7}
}

func (x *FileChangeRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileChangeRecord) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *FileChangeRecord) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *FileChangeRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileChangeRecord) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileChangeRecord) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_UNSPECIFIED
}

func (x *FileChangeRecord) GetOldHash() string {
	if x != nil {
		return x.OldHash
	}
	return ""
}

func (x *FileChangeRecord) GetNewHash() string {
	if x != nil {
		return x.NewHash
	}
	return ""
}

func (x *FileChangeRecord) GetLinesAdded() int32 {
	if x != nil {
		return x.LinesAdded
	}
	return 0
}

func (x *FileChangeRecord) GetLinesDeleted() int32 {
	if x != nil {
		return x.LinesDeleted
	}
	return 0
}

func (x *FileChangeRecord) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *FileChangeRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileChangeRecord) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetFileHistoryRequest retrieves change history for a specific file
type GetFileHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                               // File path to get history for
	SliceId       string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`          // Optional: filter by slice (empty = root slice)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // Max results (default: 50)
	FromCommit    string                 `protobuf:"bytes,4,opt,name=from_commit,json=fromCommit,proto3" json:"from_commit,omitempty"` // Pagination: start after this commit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileHistoryRequest) Reset() {
	*x = GetFileHistoryRequest{}
	mi := &file_file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileHistoryRequest) ProtoMessage() {}

func (x *GetFileHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetFileHistoryRequest) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileHistoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetFileHistoryRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *GetFileHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFileHistoryRequest) GetFromCommit() string {
	if x != nil {
		return x.FromCommit
	}
	return ""
}

type GetFileHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*FileChangeRecord    `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`         // True if more results available
	NextCommit    string                 `protobuf:"bytes,3,opt,name=next_commit,json=nextCommit,proto3" json:"next_commit,omitempty"` // Commit hash for next page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileHistoryResponse) Reset() {
	*x = GetFileHistoryResponse{}
	mi := &file_file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileHistoryResponse) ProtoMessage() {}

func (x *GetFileHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetFileHistoryResponse) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileHistoryResponse) GetChanges() []*FileChangeRecord {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *GetFileHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetFileHistoryResponse) GetNextCommit() string {
	if x != nil {
		return x.NextCommit
	}
	return ""
}

// GetDirectoryHistoryRequest retrieves change history for files under a directory
type GetDirectoryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                                                  // Directory path (empty = root)
	SliceId       string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`                                             // Optional: filter by slice
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                                               // Max results (default: 100)
	FromCommit    string                 `protobuf:"bytes,4,opt,name=from_commit,json=fromCommit,proto3" json:"from_commit,omitempty"`                                    // Pagination cursor
	ChangeTypes   []ChangeType           `protobuf:"varint,5,rep,packed,name=change_types,json=changeTypes,proto3,enum=file.v1.ChangeType" json:"change_types,omitempty"` // Optional: filter by change type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryHistoryRequest) Reset() {
	*x = GetDirectoryHistoryRequest{}
	mi := &file_file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryHistoryRequest) ProtoMessage() {}

func (x *GetDirectoryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDirectoryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDirectoryHistoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDirectoryHistoryRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *GetDirectoryHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetDirectoryHistoryRequest) GetFromCommit() string {
	if x != nil {
		return x.FromCommit
	}
	return ""
}

func (x *GetDirectoryHistoryRequest) GetChangeTypes() []ChangeType {
	if x != nil {
		return x.ChangeTypes
	}
	return nil
}

type GetDirectoryHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Changes       []*FileChangeRecord     `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	HasMore       bool                    `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCommit    string                  `protobuf:"bytes,3,opt,name=next_commit,json=nextCommit,proto3" json:"next_commit,omitempty"`
	Summary       *DirectoryChangeSummary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"` // Aggregated stats
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectoryHistoryResponse) Reset() {
	*x = GetDirectoryHistoryResponse{}
	mi := &file_file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectoryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectoryHistoryResponse) ProtoMessage() {}

func (x *GetDirectoryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectoryHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetDirectoryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetDirectoryHistoryResponse) GetChanges() []*FileChangeRecord {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *GetDirectoryHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetDirectoryHistoryResponse) GetNextCommit() string {
	if x != nil {
		return x.NextCommit
	}
	return ""
}

func (x *GetDirectoryHistoryResponse) GetSummary() *DirectoryChangeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// DirectoryChangeSummary provides aggregated change statistics
type DirectoryChangeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TotalChanges  int32                  `protobuf:"varint,2,opt,name=total_changes,json=totalChanges,proto3" json:"total_changes,omitempty"`                                                                                // Total number of changes
	FilesChanged  int32                  `protobuf:"varint,3,opt,name=files_changed,json=filesChanged,proto3" json:"files_changed,omitempty"`                                                                                // Unique files with changes
	ChangesByType map[string]int32       `protobuf:"bytes,4,rep,name=changes_by_type,json=changesByType,proto3" json:"changes_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Count by ChangeType name
	LastChange    *FileChangeRecord      `protobuf:"bytes,5,opt,name=last_change,json=lastChange,proto3" json:"last_change,omitempty"`                                                                                       // Most recent change
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryChangeSummary) Reset() {
	*x = DirectoryChangeSummary{}
	mi := &file_file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryChangeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryChangeSummary) ProtoMessage() {}

func (x *DirectoryChangeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryChangeSummary.ProtoReflect.Descriptor instead.
func (*DirectoryChangeSummary) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{12}
}

func (x *DirectoryChangeSummary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryChangeSummary) GetTotalChanges() int32 {
	if x != nil {
		return x.TotalChanges
	}
	return 0
}

func (x *DirectoryChangeSummary) GetFilesChanged() int32 {
	if x != nil {
		return x.FilesChanged
	}
	return 0
}

func (x *DirectoryChangeSummary) GetChangesByType() map[string]int32 {
	if x != nil {
		return x.ChangesByType
	}
	return nil
}

func (x *DirectoryChangeSummary) GetLastChange() *FileChangeRecord {
	if x != nil {
		return x.LastChange
	}
	return nil
}

// GetCommitChangesRequest retrieves all file changes in a commit
type GetCommitChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // Commit to get changes for
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitChangesRequest) Reset() {
	*x = GetCommitChangesRequest{}
	mi := &file_file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitChangesRequest) ProtoMessage() {}

func (x *GetCommitChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitChangesRequest.ProtoReflect.Descriptor instead.
func (*GetCommitChangesRequest) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetCommitChangesRequest) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

type GetCommitChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Changes       []*FileChangeRecord    `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes,omitempty"`
	FilesAdded    int32                  `protobuf:"varint,3,opt,name=files_added,json=filesAdded,proto3" json:"files_added,omitempty"`
	FilesModified int32                  `protobuf:"varint,4,opt,name=files_modified,json=filesModified,proto3" json:"files_modified,omitempty"`
	FilesDeleted  int32                  `protobuf:"varint,5,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	FilesRenamed  int32                  `protobuf:"varint,6,opt,name=files_renamed,json=filesRenamed,proto3" json:"files_renamed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommitChangesResponse) Reset() {
	*x = GetCommitChangesResponse{}
	mi := &file_file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommitChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommitChangesResponse) ProtoMessage() {}

func (x *GetCommitChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommitChangesResponse.ProtoReflect.Descriptor instead.
func (*GetCommitChangesResponse) Descriptor() ([]byte, []int) {
	return file_file_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetCommitChangesResponse) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *GetCommitChangesResponse) GetChanges() []*FileChangeRecord {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *GetCommitChangesResponse) GetFilesAdded() int32 {
	if x != nil {
		return x.FilesAdded
	}
	return 0
}

func (x *GetCommitChangesResponse) GetFilesModified() int32 {
	if x != nil {
		return x.FilesModified
	}
	return 0
}

func (x *GetCommitChangesResponse) GetFilesDeleted() int32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *GetCommitChangesResponse) GetFilesRenamed() int32 {
	if x != nil {
		return x.FilesRenamed
	}
	return 0
}

var File_file_service_proto protoreflect.FileDescriptor

const file_file_service_proto_rawDesc = "" +
	"\n" +
	"\x12file_service.proto\x12\afile.v1\x1a\x1cgoogle/api/annotations.proto\"H\n" +
	"\fSliceVersion\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x1d\n" +
	"\n" +
	"slice_hash\x18\x02 \x01(\tR\tsliceHash\"\xaa\x01\n" +
	"\x12ListEntriesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12!\n" +
	"\vcommit_hash\x18\n" +
	" \x01(\tH\x00R\n" +
	"commitHash\x12<\n" +
	"\rslice_version\x18\v \x01(\v2\x15.file.v1.SliceVersionH\x00R\fsliceVersionB\t\n" +
	"\aversion\"\x95\x01\n" +
	"\x13ListEntriesResponse\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.file.v1.DirectoryEntryR\aentries\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\"\x97\x01\n" +
	"\x0eDirectoryEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.file.v1.EntryTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12!\n" +
	"\fhas_children\x18\x05 \x01(\bR\vhasChildren\"\x90\x01\n" +
	"\x0eGetFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\vcommit_hash\x18\n" +
	" \x01(\tH\x00R\n" +
	"commitHash\x12<\n" +
	"\rslice_version\x18\v \x01(\v2\x15.file.v1.SliceVersionH\x00R\fsliceVersionB\t\n" +
	"\aversion\"4\n" +
	"\x0fGetFileResponse\x12!\n" +
	"\x04file\x18\x01 \x01(\v2\r.file.v1.FileR\x04file\"\\\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"\x8f\x03\n" +
	"\x10FileChangeRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\tR\n" +
	"commitHash\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x19\n" +
	"\bold_path\x18\x05 \x01(\tR\aoldPath\x124\n" +
	"\vchange_type\x18\x06 \x01(\x0e2\x13.file.v1.ChangeTypeR\n" +
	"changeType\x12\x19\n" +
	"\bold_hash\x18\a \x01(\tR\aoldHash\x12\x19\n" +
	"\bnew_hash\x18\b \x01(\tR\anewHash\x12\x1f\n" +
	"\vlines_added\x18\t \x01(\x05R\n" +
	"linesAdded\x12#\n" +
	"\rlines_deleted\x18\n" +
	" \x01(\x05R\flinesDeleted\x12\x16\n" +
	"\x06author\x18\v \x01(\tR\x06author\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\r \x01(\x03R\ttimestamp\"}\n" +
	"\x15GetFileHistoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vfrom_commit\x18\x04 \x01(\tR\n" +
	"fromCommit\"\x89\x01\n" +
	"\x16GetFileHistoryResponse\x123\n" +
	"\achanges\x18\x01 \x03(\v2\x19.file.v1.FileChangeRecordR\achanges\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_commit\x18\x03 \x01(\tR\n" +
	"nextCommit\"\xba\x01\n" +
	"\x1aGetDirectoryHistoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vfrom_commit\x18\x04 \x01(\tR\n" +
	"fromCommit\x126\n" +
	"\fchange_types\x18\x05 \x03(\x0e2\x13.file.v1.ChangeTypeR\vchangeTypes\"\xc9\x01\n" +
	"\x1bGetDirectoryHistoryResponse\x123\n" +
	"\achanges\x18\x01 \x03(\v2\x19.file.v1.FileChangeRecordR\achanges\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_commit\x18\x03 \x01(\tR\n" +
	"nextCommit\x129\n" +
	"\asummary\x18\x04 \x01(\v2\x1f.file.v1.DirectoryChangeSummaryR\asummary\"\xd0\x02\n" +
	"\x16DirectoryChangeSummary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12#\n" +
	"\rtotal_changes\x18\x02 \x01(\x05R\ftotalChanges\x12#\n" +
	"\rfiles_changed\x18\x03 \x01(\x05R\ffilesChanged\x12Z\n" +
	"\x0fchanges_by_type\x18\x04 \x03(\v22.file.v1.DirectoryChangeSummary.ChangesByTypeEntryR\rchangesByType\x12:\n" +
	"\vlast_change\x18\x05 \x01(\v2\x19.file.v1.FileChangeRecordR\n" +
	"lastChange\x1a@\n" +
	"\x12ChangesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\":\n" +
	"\x17GetCommitChangesRequest\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\"\x82\x02\n" +
	"\x18GetCommitChangesResponse\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x123\n" +
	"\achanges\x18\x02 \x03(\v2\x19.file.v1.FileChangeRecordR\achanges\x12\x1f\n" +
	"\vfiles_added\x18\x03 \x01(\x05R\n" +
	"filesAdded\x12%\n" +
	"\x0efiles_modified\x18\x04 \x01(\x05R\rfilesModified\x12#\n" +
	"\rfiles_deleted\x18\x05 \x01(\x05R\ffilesDeleted\x12#\n" +
	"\rfiles_renamed\x18\x06 \x01(\x05R\ffilesRenamed*V\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fENTRY_TYPE_FILE\x10\x01\x12\x18\n" +
	"\x14ENTRY_TYPE_DIRECTORY\x10\x02*\x86\x01\n" +
	"\n" +
	"ChangeType\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCHANGE_TYPE_ADD\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_MODIFY\x10\x02\x12\x16\n" +
	"\x12CHANGE_TYPE_DELETE\x10\x03\x12\x16\n" +
	"\x12CHANGE_TYPE_RENAME\x10\x042\x89\b\n" +
	"\vFileService\x12\xec\x01\n" +
	"\vListEntries\x12\x1b.file.v1.ListEntriesRequest\x1a\x1c.file.v1.ListEntriesResponse\"\xa1\x01\x82\xd3\xe4\x93\x02\x9a\x01Z\x13\x12\x11/v1/files/entriesZ7\x125/v1/slices/{slice_version.slice_id}/entries/{path=**}Z-\x12+/v1/slices/{slice_version.slice_id}/entries\x12\x1b/v1/files/entries/{path=**}\x12\xcc\x01\n" +
	"\aGetFile\x12\x17.file.v1.GetFileRequest\x1a\x18.file.v1.GetFileResponse\"\x8d\x01\x82\xd3\xe4\x93\x02\x86\x01Z\v\x12\t/v1/filesZ5\x123/v1/slices/{slice_version.slice_id}/files/{path=**}Z+\x12)/v1/slices/{slice_version.slice_id}/files\x12\x13/v1/files/{path=**}\x12\xa7\x01\n" +
	"\x0eGetFileHistory\x12\x1e.file.v1.GetFileHistoryRequest\x1a\x1f.file.v1.GetFileHistoryResponse\"T\x82\xd3\xe4\x93\x02NZ/\x12-/v1/slices/{slice_id}/files/history/{path=**}\x12\x1b/v1/files/history/{path=**}\x12\x8c\x02\n" +
	"\x13GetDirectoryHistory\x12#.file.v1.GetDirectoryHistoryRequest\x1a$.file.v1.GetDirectoryHistoryResponse\"\xa9\x01\x82\xd3\xe4\x93\x02\xa2\x01Z\x19\x12\x17/v1/directories/historyZ5\x123/v1/slices/{slice_id}/directories/history/{path=**}Z+\x12)/v1/slices/{slice_id}/directories/history\x12!/v1/directories/history/{path=**}\x12\x82\x01\n" +
	"\x10GetCommitChanges\x12 .file.v1.GetCommitChangesRequest\x1a!.file.v1.GetCommitChangesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/commits/{commit_hash}/changesB-Z+github.com/niczy/gitslice/proto/file;filev1b\x06proto3"

var (
	file_file_service_proto_rawDescOnce sync.Once
	file_file_service_proto_rawDescData []byte
)

func file_file_service_proto_rawDescGZIP() []byte {
	file_file_service_proto_rawDescOnce.Do(func() {
		file_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_service_proto_rawDesc), len(file_file_service_proto_rawDesc)))
	})
	return file_file_service_proto_rawDescData
}

var file_file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_file_service_proto_goTypes = []any{
	(EntryType)(0),                      // 0: file.v1.EntryType
	(ChangeType)(0),                     // 1: file.v1.ChangeType
	(*SliceVersion)(nil),                // 2: file.v1.SliceVersion
	(*ListEntriesRequest)(nil),          // 3: file.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),         // 4: file.v1.ListEntriesResponse
	(*DirectoryEntry)(nil),              // 5: file.v1.DirectoryEntry
	(*GetFileRequest)(nil),              // 6: file.v1.GetFileRequest
	(*GetFileResponse)(nil),             // 7: file.v1.GetFileResponse
	(*File)(nil),                        // 8: file.v1.File
	(*FileChangeRecord)(nil),            // 9: file.v1.FileChangeRecord
	(*GetFileHistoryRequest)(nil),       // 10: file.v1.GetFileHistoryRequest
	(*GetFileHistoryResponse)(nil),      // 11: file.v1.GetFileHistoryResponse
	(*GetDirectoryHistoryRequest)(nil),  // 12: file.v1.GetDirectoryHistoryRequest
	(*GetDirectoryHistoryResponse)(nil), // 13: file.v1.GetDirectoryHistoryResponse
	(*DirectoryChangeSummary)(nil),      // 14: file.v1.DirectoryChangeSummary
	(*GetCommitChangesRequest)(nil),     // 15: file.v1.GetCommitChangesRequest
	(*GetCommitChangesResponse)(nil),    // 16: file.v1.GetCommitChangesResponse
	nil,                                 // 17: file.v1.DirectoryChangeSummary.ChangesByTypeEntry
}
var file_file_service_proto_depIdxs = []int32{
	2,  // 0: file.v1.ListEntriesRequest.slice_version:type_name -> file.v1.SliceVersion
	5,  // 1: file.v1.ListEntriesResponse.entries:type_name -> file.v1.DirectoryEntry
	0,  // 2: file.v1.DirectoryEntry.type:type_name -> file.v1.EntryType
	2,  // 3: file.v1.GetFileRequest.slice_version:type_name -> file.v1.SliceVersion
	8,  // 4: file.v1.GetFileResponse.file:type_name -> file.v1.File
	1,  // 5: file.v1.FileChangeRecord.change_type:type_name -> file.v1.ChangeType
	9,  // 6: file.v1.GetFileHistoryResponse.changes:type_name -> file.v1.FileChangeRecord
	1,  // 7: file.v1.GetDirectoryHistoryRequest.change_types:type_name -> file.v1.ChangeType
	9,  // 8: file.v1.GetDirectoryHistoryResponse.changes:type_name -> file.v1.FileChangeRecord
	14, // 9: file.v1.GetDirectoryHistoryResponse.summary:type_name -> file.v1.DirectoryChangeSummary
	17, // 10: file.v1.DirectoryChangeSummary.changes_by_type:type_name -> file.v1.DirectoryChangeSummary.ChangesByTypeEntry
	9,  // 11: file.v1.DirectoryChangeSummary.last_change:type_name -> file.v1.FileChangeRecord
	9,  // 12: file.v1.GetCommitChangesResponse.changes:type_name -> file.v1.FileChangeRecord
	3,  // 13: file.v1.FileService.ListEntries:input_type -> file.v1.ListEntriesRequest
	6,  // 14: file.v1.FileService.GetFile:input_type -> file.v1.GetFileRequest
	10, // 15: file.v1.FileService.GetFileHistory:input_type -> file.v1.GetFileHistoryRequest
	12, // 16: file.v1.FileService.GetDirectoryHistory:input_type -> file.v1.GetDirectoryHistoryRequest
	15, // 17: file.v1.FileService.GetCommitChanges:input_type -> file.v1.GetCommitChangesRequest
	4,  // 18: file.v1.FileService.ListEntries:output_type -> file.v1.ListEntriesResponse
	7,  // 19: file.v1.FileService.GetFile:output_type -> file.v1.GetFileResponse
	11, // 20: file.v1.FileService.GetFileHistory:output_type -> file.v1.GetFileHistoryResponse
	13, // 21: file.v1.FileService.GetDirectoryHistory:output_type -> file.v1.GetDirectoryHistoryResponse
	16, // 22: file.v1.FileService.GetCommitChanges:output_type -> file.v1.GetCommitChangesResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_file_service_proto_init() }
func file_file_service_proto_init() {
	if File_file_service_proto != nil {
		return
	}
	file_file_service_proto_msgTypes[1].OneofWrappers = []any{
		(*ListEntriesRequest_CommitHash)(nil),
		(*ListEntriesRequest_SliceVersion)(nil),
	}
	file_file_service_proto_msgTypes[4].OneofWrappers = []any{
		(*GetFileRequest_CommitHash)(nil),
		(*GetFileRequest_SliceVersion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_service_proto_rawDesc), len(file_file_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_service_proto_goTypes,
		DependencyIndexes: file_file_service_proto_depIdxs,
		EnumInfos:         file_file_service_proto_enumTypes,
		MessageInfos:      file_file_service_proto_msgTypes,
	}.Build()
	File_file_service_proto = out.File
	file_file_service_proto_goTypes = nil
	file_file_service_proto_depIdxs = nil
}
