load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "models",
    srcs = [
        "changeset.go",
        "commit.go",
        "conflict.go",
        "file_change.go",
        "slice.go",
    ],
    importpath = "github.com/niczy/gitslice/internal/models",
)
