load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "gateway_service_lib",
    srcs = ["main.go"],
    importpath = "github.com/niczy/gitslice/gateway_service",
    deps = [
        "//internal/common",
        "//internal/config",
        "//proto/admin:admin_go",
        "//proto/file:file_go",
        "@com_github_grpc_ecosystem_grpc_gateway_v2//runtime:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes:go_default_library",
        "@org_golang_google_grpc//credentials/insecure:go_default_library",
        "@org_golang_google_grpc//status:go_default_library",
    ],
)

go_binary(
    name = "gateway_service",
    embed = [":gateway_service_lib"],
)

go_test(
    name = "gateway_service_test",
    srcs = ["main_test.go"],
    embed = [":gateway_service_lib"],
    deps = [
        "//internal/common",
        "//internal/models",
        "//internal/services/admin",
        "//internal/services/file",
        "//internal/services/slice",
        "//internal/storage",
        "//proto/file:file_go",
        "@org_golang_google_grpc//:go_default_library",
    ],
)
