import { index, route } from '@react-router/dev/routes';

export default [
  route('sign-in/sso-callback', 'routes/sign-in.sso-callback.jsx'),
  route('sign-up/sso-callback', 'routes/sign-up.sso-callback.jsx'),
  route('sign-in', 'routes/sign-in.jsx'),
  route('sign-up', 'routes/sign-up.jsx'),
  route('sign-out', 'routes/sign-out.jsx'),
  route('auth/session', 'routes/auth.session.jsx'),
  route('auth/dev-login', 'routes/auth.dev-login.jsx'),
  route('auth/dev-logout', 'routes/auth.dev-logout.jsx'),
  route('auth/device', 'routes/auth.device.jsx'),
  route('auth/device/approve', 'routes/auth.device-approve.jsx'),
  route('auth/*', 'routes/auth.$.jsx'),
  route('raw/*', 'routes/raw.$.jsx'),
  route('ws/agent-runners', 'routes/ws.agent-runners.jsx'),
  route('v1/*', 'routes/v1.$.jsx'),
  index('routes/app-shell.jsx'),
  route('login', 'routes/login.jsx'),
  route('docs', 'routes/docs.jsx'),
  route('docs.md', 'routes/docs-md.jsx'),
  route('projects', 'routes/projects.jsx'),
  route('profile', 'routes/profile.jsx'),
  route('settings', 'routes/settings.jsx'),
  route('settings/ci', 'routes/settings.ci.jsx'),
  route('settings/ci/runners', 'routes/settings.ci.runners.jsx'),
  route('settings/ci/runners/:runnerId', 'routes/settings.ci.runners.$runnerId.jsx'),
  route('settings/ci/runs', 'routes/settings.ci.runs.jsx'),
  route('admin', 'routes/admin.jsx'),
  route('browser', 'routes/browser.jsx'),
  route('browser/:sliceId/commits', 'routes/browser.$sliceId.commits.jsx'),
  route('browser/:sliceId/changesets', 'routes/browser.$sliceId.changesets.jsx'),
  route('browser/:sliceId/agents', 'routes/browser.$sliceId.agents.jsx'),
  route('browser/:sliceId/settings', 'routes/browser.$sliceId.settings.jsx'),
  route('browser/:sliceId', 'routes/browser.$sliceId.jsx'),
  route('slices', 'routes/slices.jsx'),
  route('slices/:sliceId/commits', 'routes/slices.$sliceId.commits.jsx'),
  route('slices/:sliceId/changesets', 'routes/slices.$sliceId.changesets.jsx'),
  route('slices/:sliceId/agents', 'routes/slices.$sliceId.agents.jsx'),
  route('slices/:sliceId/settings', 'routes/slices.$sliceId.settings.jsx'),
  route('slices/:sliceId', 'routes/slices.$sliceId.jsx'),
  route('diff/:commitHash', 'routes/diff.$commitHash.jsx'),
  route('changesets/:changesetId', 'routes/changesets.$changesetId.jsx'),
  route('*', 'routes/catchall.jsx'),
];
