// ---------------------------------------------------------------------------
// API and authentication helpers
// ---------------------------------------------------------------------------

import { getSignedInUsername } from '../auth.js';

// Browser data requests stay same-origin so auth cookies continue to work
// when the web tier proxies API traffic to a different origin.
export const apiBaseUrl = '';

export function currentUsername() {
  return getSignedInUsername();
}

export function fetchWithAuth(url, options = {}) {
  const headers = new Headers(options.headers || {});
  const username = currentUsername();
  if (username) {
    headers.set('Authorization', `User ${username}`);
  }
  return fetch(url, { ...options, credentials: 'include', headers });
}

async function readErrorMessage(response, fallback) {
  let detail = '';
  try {
    const text = await response.text();
    if (text) {
      try {
        const payload = JSON.parse(text);
        detail = payload?.message || payload?.error || '';
      } catch {
        detail = text;
      }
    }
  } catch {
    detail = '';
  }
  return detail ? `${fallback}: ${detail}` : `${fallback} (${response.status})`;
}

export async function fetchEnvironments() {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/environments?limit=500&offset=0`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load environments'));
  }
  const payload = await response.json();
  return payload?.environments || [];
}

export async function fetchRepoBindings() {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/repos/bindings`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load repo bindings'));
  }
  const payload = await response.json();
  return payload?.bindings || [];
}

function decodeBase64(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

function encodeBase64(bytes) {
  let binary = '';
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary);
}

function normalizeAgentPublicKeyInput(input) {
  const trimmed = String(input || '').trim();
  if (!trimmed) {
    throw new Error('Public key is required.');
  }

  const rawBase64 = trimmed
    .replace('-----BEGIN PUBLIC KEY-----', '')
    .replace('-----END PUBLIC KEY-----', '')
    .replace(/\s+/g, '');
  const bytes = decodeBase64(rawBase64);
  if (bytes.length === 32) {
    return encodeBase64(bytes);
  }

  const expectedPrefix = [0x30, 0x2a, 0x30, 0x05, 0x06, 0x03, 0x2b, 0x65, 0x70, 0x03, 0x21, 0x00];
  const matchesPrefix = bytes.length === expectedPrefix.length + 32 && expectedPrefix.every((value, index) => bytes[index] === value);
  if (matchesPrefix) {
    return encodeBase64(bytes.slice(expectedPrefix.length));
  }

  throw new Error('Unsupported public key format. Paste the .pub file generated by gs auth keygen or raw base64 ed25519 public key bytes.');
}

export async function fetchAgentKeys() {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load agent keys'));
  }
  const payload = await response.json();
  return payload?.keys || [];
}

export async function createAgentKey({ name, publicKeyText }) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name,
      algorithm: 'ed25519',
      publicKey: normalizeAgentPublicKeyInput(publicKeyText),
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to add agent key'));
  }
  return response.json();
}

export async function revokeAgentKey(keyId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/auth/agent/keys/${encodeURIComponent(keyId)}`, {
    method: 'DELETE',
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to revoke agent key'));
  }
}

export async function getSliceEnvironment(sliceId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/slices/${encodeURIComponent(sliceId)}/environment`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load slice environment'));
  }
  return response.json();
}

export async function getSliceVisibility(sliceId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/slices/${encodeURIComponent(sliceId)}/visibility`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load slice visibility'));
  }
  return response.json();
}

export async function updateSliceVisibility(sliceId, { visibility, pathPropagationMode }) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/slices/${encodeURIComponent(sliceId)}:setVisibility`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      visibility,
      pathPropagationMode,
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to update slice visibility'));
  }
  return response.json();
}

export async function getPathVisibility({ workspaceId, path }) {
  const params = new URLSearchParams({
    workspace_id: workspaceId,
    path,
  });
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/fs:visibility?${params.toString()}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load path visibility'));
  }
  return response.json();
}

export async function updatePathVisibility({ path, visibility, recursive = false }) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/fs:visibility`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      path,
      visibility,
      recursive,
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to update path visibility'));
  }
  return response.json();
}

export async function updateSliceEnvironment(sliceId, environment) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/slices/${encodeURIComponent(sliceId)}/environment`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ environment }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to update slice environment'));
  }
  return response.json();
}

export async function createRevertChangeset(commitHash, sliceId = '') {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/commits/${encodeURIComponent(commitHash)}/changes/revert`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      sliceId: sliceId || undefined,
    }),
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to create revert changeset'));
  }
  return response.json();
}

export async function getChangesetDiff(changesetId, snapshotVersion) {
  const query = new URLSearchParams();
  if (typeof snapshotVersion === 'number' && snapshotVersion > 0) {
    query.set('snapshot_version', String(snapshotVersion));
  }
  const suffix = query.toString() ? `?${query.toString()}` : '';
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/changesets/${encodeURIComponent(changesetId)}/diff${suffix}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load changeset diff'));
  }
  return response.json();
}

export async function listChangesetSnapshots(changesetId, limit = 100) {
  const query = new URLSearchParams();
  if (typeof limit === 'number' && limit > 0) {
    query.set('limit', String(limit));
  }
  const suffix = query.toString() ? `?${query.toString()}` : '';
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/changesets/${encodeURIComponent(changesetId)}/snapshots${suffix}`);
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to load changeset snapshots'));
  }
  return response.json();
}

export async function mergeChangeset(changesetId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/changesets/${encodeURIComponent(changesetId)}/merge`, {
    method: 'POST',
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to merge changeset'));
  }
  return response.json();
}

export async function closeChangeset(changesetId) {
  const response = await fetchWithAuth(`${apiBaseUrl}/v1/changesets/${encodeURIComponent(changesetId)}/close`, {
    method: 'POST',
  });
  if (!response.ok) {
    throw new Error(await readErrorMessage(response, 'Unable to close changeset'));
  }
  return response.json();
}
