load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "file",
    srcs = ["server.go"],
    importpath = "github.com/niczy/gitslice/internal/services/file",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/models",
        "//internal/storage",
        "//proto/file",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
