package gscli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const agentInstructionFileMarker = "<!-- gitslice-agent-local-instructions:v1 -->"

var agentInstructionFileNames = []string{"AGENTS.md", "CLAUDE.md"}

func ensureAgentInstructionFiles(root string) error {
	for _, name := range agentInstructionFileNames {
		path := filepath.Join(root, name)
		if _, err := os.Lstat(path); err == nil {
			continue
		} else if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("inspect %s: %w", name, err)
		}

		if err := os.WriteFile(path, []byte(agentInstructionFileContent(name)), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", name, err)
		}
	}
	return nil
}

func agentInstructionFileContent(name string) string {
	title := "Local Agent Instructions"
	if name == "CLAUDE.md" {
		title = "Claude Local Agent Instructions"
	}
	lines := []string{
		"# " + title,
		agentInstructionFileMarker,
		"",
		"This file was generated by `gs agent` for this local session checkout.",
		"It is local guidance for coding agents and is intentionally ignored by `gs slice` status, diff, export, and publish.",
		"",
		"Work in this directory only for the current agent session. Other sessions use separate checkouts.",
		"",
		"Useful `gs` workflow:",
		"- Run `gs context --json` first when you need slice, checkout, or changeset context.",
		"- Use `gs slice status` and `gs slice diff` to inspect local edits.",
		"- Use `gs slice export` to create or update a changeset when asked.",
		"- Use `gs slice publish` only when explicitly asked to publish and merge the local changes.",
		"",
		"Operational notes:",
		"- Keep `.gs/` intact; it contains the local checkout metadata.",
		"- Do not assume this checkout is a git repository.",
		"- Prefer existing project instructions in files that are tracked by the slice when they conflict with this generated file.",
	}
	return strings.Join(lines, "\n") + "\n"
}

func isAgentInstructionFilePath(relPath string) bool {
	cleaned := filepath.ToSlash(filepath.Clean(strings.TrimSpace(relPath)))
	switch cleaned {
	case "AGENTS.md", "CLAUDE.md":
		return true
	default:
		return false
	}
}

func shouldIgnoreGeneratedAgentInstructionFile(root, relPath string) bool {
	if !isAgentInstructionFilePath(relPath) {
		return false
	}
	data, err := os.ReadFile(filepath.Join(root, relPath))
	if err != nil {
		return false
	}
	return strings.Contains(string(data), agentInstructionFileMarker)
}
