load("@rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "gs_cli_lib",
    srcs = [
        "cache.go",
        "checkout_parallel.go",
        "commands_changeset.go",
        "commands_conflict.go",
        "commands_misc.go",
        "commands_slice.go",
        "help.go",
        "main.go",
        "metadata.go",
        "utils.go",
    ],
    importpath = "github.com/niczy/gitslice/gs_cli",
    visibility = ["//visibility:private"],
    deps = [
        "//proto/admin",
        "//proto/slice",
        "@org_golang_google_grpc",
        "@org_golang_google_grpc//credentials/insecure",
    ],
)

go_binary(
    name = "gs_cli",
    embed = [":gs_cli_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "gs_cli_test",
    srcs = [
        "cache_test.go",
        "checkout_parallel_test.go",
    ],
    embed = [":gs_cli_lib"],
)
