package gscli

import "fmt"

func printHelp() {
	fmt.Println("Usage: gs <command> [options]")
	fmt.Println("\nGlobal behavior:")
	fmt.Println("  --non-interactive   Fail instead of opening interactive flows (also GS_NON_INTERACTIVE=1)")
	fmt.Println("  --version, -v       Print CLI version information")
	fmt.Println("\nGlobal auth resolution:")
	fmt.Println("  1. --api-key")
	fmt.Println("  2. GS_API_KEY")
	fmt.Println("  3. GS_API_KEY_FILE")
	fmt.Println("  4. ~/.gitslice/credentials.json")
	fmt.Println("  5. legacy username auth (--user, GS_USERNAME, ~/.gitslice/user)")
	fmt.Println("\nCommands:")
	fmt.Println("  auth       Manage CLI auth, agent keys, and key-based login")
	fmt.Println("  git        Git integration helpers")
	fmt.Println("  config     Manage local CLI configuration")
	fmt.Println("  slice       Manage slices")
	fmt.Println("  changeset   Manage change lists")
	fmt.Println("  conflict    Detect and resolve conflicts")
	fmt.Println("  import      Import external repositories")
	fmt.Println("  repo        Bind remote repositories into your home slice")
	fmt.Println("  file        Browse files and file history")
	fmt.Println("  fs          Remote home filesystem operations")
	fmt.Println("  update      Update the gs CLI (alias: upgrade)")
	fmt.Println("  jobs        Inspect detached CLI jobs for long-running commands")
	fmt.Println("  cache       Inspect and clean local checkout/cache state")
	fmt.Println("  doctor      Check auth, slice binding, cache, and service health")
	fmt.Println("  context     Print agent-friendly current auth/checkout/changeset context")
	fmt.Println("  ci          Run and inspect Gitslice CI checks")
	fmt.Println("  runner      Manage and run CI executors")
	fmt.Println("  agent       Start and run local coding agents")
	fmt.Println("\nLegacy aliases:")
	fmt.Println("  login      Alias for interactive auth login/status")
	fmt.Println("  logout     Alias for auth logout")
	fmt.Println("  init       Alias for slice bind")
	fmt.Println("  status     Alias for slice status")
	fmt.Println("  log        Alias for slice history")
	fmt.Println("  root       Alias for slice root")
	fmt.Println("\nExamples:")
	fmt.Println("  gs config endpoint set api.agenttools.dev:443 --tls")
	fmt.Println("  gs auth status --json")
	fmt.Println("  git config --global credential.https://api.agenttools.dev.helper \"!gs git credential\"")
	fmt.Println("  gs context --json")
	fmt.Println("  gs slice checkout home_nic --json")
	fmt.Println("  gs slice status --json")
	fmt.Println("  gs repo ensure https://github.com/org/repo.git /nic/vendor/repo --json")
	fmt.Println("  gs fs write /nic/app/config.json -f config.json --json")
	fmt.Println("  gs repo import https://github.com/org/repo.git /nic/vendor/repo --detach --json")
	fmt.Println("  gs ci status --json")
	fmt.Println("  gs runner list --json")
	fmt.Println("  gs agent run --dir ~/gitslice-agents --agent codex")
	fmt.Println("  gs update")
	fmt.Println("  gs jobs wait job_123 --json")
	fmt.Println("\nUse 'gs <command> --help' for more information about a command.")
}

func printAgentHelp() {
	fmt.Println("Usage: gs agent <command> [options]")
	fmt.Println("Start and run local coding agents for web-controlled sessions.")
	fmt.Println("\nCommands:")
	fmt.Println("  start      Start a background local agent runner")
	fmt.Println("  run        Run a local agent runner in the foreground")
	fmt.Println("  input      Send input to an agent session")
	fmt.Println("  interrupt  Interrupt an agent session")
	fmt.Println("  stop       Stop an agent session")
	fmt.Println("\nExamples:")
	fmt.Println("  gs agent start --dir ~/gitslice-agents --agent codex --json")
	fmt.Println("  gs agent run --dir ~/gitslice-agents --agent codex")
	fmt.Println("  gs agent run --dir ~/gitslice-agents --agent codex --codex-mode exec")
	fmt.Println("  gs agent run --dir ~/gitslice-agents --agent claude --claude-mode print")
	fmt.Println("  gs agent run --dir ~/gitslice-agents -- ./my-agent-script")
	fmt.Println("  gs agent input sess_123 \"summarize the current diff\"")
}

func printCIHelp() {
	fmt.Println("Usage: gs ci <command> [options]")
	fmt.Println("Plan and inspect Gitslice CI runs.")
	fmt.Println("\nCommands:")
	fmt.Println("  run      Start a CI run for the current or specified changeset")
	fmt.Println("  status   Show CI status for a run or current changeset")
	fmt.Println("  logs     Stream logs for a run or job")
	fmt.Println("\nExamples:")
	fmt.Println("  gs ci run --changeset chg_123 --json")
	fmt.Println("  gs ci status --json")
	fmt.Println("  gs ci logs --run ci_run_123 --job ci_job_123")
}

func printRunnerHelp() {
	fmt.Println("Usage: gs runner <command> [options]")
	fmt.Println("Manage and run user-hosted CI executors.")
	fmt.Println("\nManagement commands:")
	fmt.Println("  pool      List or inspect runner pools")
	fmt.Println("  list      List registered runners")
	fmt.Println("  show      Show runner details")
	fmt.Println("  token     Create registration tokens")
	fmt.Println("  disable   Disable a runner")
	fmt.Println("  enable    Enable a runner")
	fmt.Println("  revoke    Revoke a runner credential")
	fmt.Println("  jobs      Show runner job history")
	fmt.Println("  queue     Inspect queued CI jobs")
	fmt.Println("\nHost commands:")
	fmt.Println("  enroll    Enroll this VM using a registration token")
	fmt.Println("  register  Alias for enroll")
	fmt.Println("  start     Start polling and executing CI jobs")
	fmt.Println("  status    Show this runner host status")
	fmt.Println("  doctor    Diagnose runner host setup")
	fmt.Println("  unenroll  Remove local runner credentials")
	fmt.Println("\nExamples:")
	fmt.Println("  gs runner pool list --json")
	fmt.Println("  gs runner pool show default --json")
	fmt.Println("  gs runner token create --name vm-1 --pool default --ttl 30m --json")
	fmt.Println("  gs runner register --token <runner-registration-token>")
	fmt.Println("  gs runner start --executor docker")
	fmt.Println("  gs runner revoke ci_runner_123 --requeue-leased")
	fmt.Println("  gs runner queue list --pool default --json")
	fmt.Println("  gs runner queue explain --pool default --image golang:1.24")
}

func printUpdateHelp() {
	fmt.Println("Usage: gs update [options]")
	fmt.Println("Alias: gs upgrade")
	fmt.Println("\nOptions:")
	fmt.Println("  --repo <url>        Git repository URL to install from")
	fmt.Println("  --ref <ref>         Git branch, tag, or ref to install")
	fmt.Println("  --install-dir <dir> Directory where gs should be installed")
	fmt.Println("  --dry-run           Print the update plan without changing files")
	fmt.Println("  --json              Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs update")
	fmt.Println("  gs update --ref main")
	fmt.Println("  gs update --ref v0.3.1")
	fmt.Println("  gs upgrade --dry-run")
}

func printGitHelp() {
	fmt.Println("Usage: gs git <command> [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  credential  Print credentials for Git's credential helper protocol")
	fmt.Println("\nExamples:")
	fmt.Println("  gs config endpoint set api.agenttools.dev:443 --tls")
	fmt.Println("  git config --global credential.https://api.agenttools.dev.helper \"!gs git credential\"")
	fmt.Println("  gs git credential get")
}

func printConfigHelp() {
	fmt.Println("Usage: gs config <command> [options]")
	fmt.Println("Most config commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  endpoint        Show effective endpoint settings")
	fmt.Println("  endpoint set    Persist endpoint settings in ~/.gitslice/config.json")
	fmt.Println("  endpoint clear  Remove persisted endpoint settings")
	fmt.Println("\nExamples:")
	fmt.Println("  gs config endpoint")
	fmt.Println("  gs config endpoint --json")
	fmt.Println("  gs config endpoint set api.agenttools.dev:443 --tls")
	fmt.Println("  gs config endpoint set api.gitslice.io:443 --tls")
	fmt.Println("  gs config endpoint clear")
}

func printAuthHelp() {
	fmt.Println("Usage: gs auth <command> [options]")
	fmt.Println("Most auth commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  keygen   Generate a local ed25519 agent keypair")
	fmt.Println("  signup   Sign up with an agent private key and store bearer credentials")
	fmt.Println("  login    Log in with an enrolled agent private key or browser sign-in via --device")
	fmt.Println("  ensure   Ensure the CLI is authenticated, optionally by logging in with --key")
	fmt.Println("  status   Show the current stored auth state")
	fmt.Println("  logout   Clear stored bearer credentials or legacy auth")
	fmt.Println("  keys     Manage enrolled agent keys")
	fmt.Println("  claim-token Create a one-time account claim URL for attaching a human sign-in")
	fmt.Println("\nExamples:")
	fmt.Println("  gs auth keygen --out ~/.config/gitslice/agent.pem")
	fmt.Println("  gs auth signup --username nic --email nic@example.com --name \"Nic\" --key ~/.config/gitslice/agent.pem --json")
	fmt.Println("  gs auth login --key ~/.config/gitslice/agent.pem --json")
	fmt.Println("  gs auth claim-token --json")
	fmt.Println("  gs auth ensure --key ~/.config/gitslice/agent.pem --json")
	fmt.Println("  gs auth status --json")
}

func printAuthKeysHelp() {
	fmt.Println("Usage: gs auth keys <command> [options]")
	fmt.Println("Most auth key commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  list     List enrolled agent keys")
	fmt.Println("  add      Add an agent public key to the current account")
	fmt.Println("  revoke   Revoke an enrolled agent key by ID")
	fmt.Println("\nExamples:")
	fmt.Println("  gs auth keys list --json")
	fmt.Println("  gs auth keys add --name ci-runner --public-key ~/.config/gitslice/agent.pub --json")
	fmt.Println("  gs auth keys revoke ak_123 --json")
}

func printSliceHelp() {
	fmt.Println("Usage: gs slice <command> [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  list      List your slices")
	fmt.Println("  bind      Bind the current directory to a slice without checking files out")
	fmt.Println("  ensure    Ensure a focused slice exists for a stable name")
	fmt.Println("  create    Create a focused slice from one or more published folders")
	fmt.Println("  checkout  Checkout a slice to ./<slice-name> using its slice ID or ref (--here for current directory)")
	fmt.Println("  clone     Alias for checkout")
	fmt.Println("  status    Show the current slice checkout status (local by default; add --remote for remote head)")
	fmt.Println("  visibility Inspect or change slice visibility")
	fmt.Println("  pull      Alias for sync")
	fmt.Println("  sync      Sync the current checked out slice in place")
	fmt.Println("  publish   Create/update or reuse the tracked changeset and merge it")
	fmt.Println("  export    Create/update or reuse the tracked changeset without merging")
	fmt.Println("  tree      Print a slice file tree")
	fmt.Println("  list-files Alias for tree")
	fmt.Println("  history   Show slice commit history")
	fmt.Println("  root      Show root slice information")
	fmt.Println("  search    Search file contents in the current local slice checkout (--regex, --glob, --json)")
	fmt.Println("  diff      Show local changes for the current slice checkout (--summary, --stat, --name-only)")
	fmt.Println("  restore   Restore local files back to the recorded slice state (--dry-run to preview)")
	fmt.Println("  checkouts List globally tracked local slice checkouts")
	fmt.Println("  delete    Delete a custom slice")
	fmt.Println("  rename    Rename a slice (update display name)")
	fmt.Println("  folder    Add or remove tracked folders for a custom slice")
	fmt.Println("\nExamples:")
	fmt.Println("  gs slice list --json")
	fmt.Println("  gs slice bind root --json")
	fmt.Println("  gs slice ensure ui-refresh apps/web --json")
	fmt.Println("  gs slice checkout nic/ui-refresh --json")
	fmt.Println("  gs slice checkout nic/ui-refresh --here --json")
	fmt.Println("  gs slice status --json")
	fmt.Println("  gs slice visibility get nic/ui-refresh --json")
	fmt.Println("  gs slice visibility set nic/ui-refresh public --propagate public --json")
	fmt.Println("  gs slice tree --slice nic/ui-refresh --json")
	fmt.Println("  gs slice history nic/ui-refresh --json")
	fmt.Println("  gs slice diff --summary")
	fmt.Println("  gs slice export --json")
	fmt.Println("  gs slice publish --json")
}

func printCacheHelp() {
	fmt.Println("Usage: gs cache <command> [options]")
	fmt.Println("Most cache commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  stats     Show local cache size and tracked checkout summary")
	fmt.Println("  prune     Remove stale tracked checkout records")
	fmt.Println("  clear     Remove cached objects and/or tracked checkout records")
	fmt.Println("\nExamples:")
	fmt.Println("  gs cache stats --json")
	fmt.Println("  gs cache prune --json")
	fmt.Println("  gs cache clear --objects --json")
}

func printJobsHelp() {
	fmt.Println("Usage: gs jobs <command> [options]")
	fmt.Println("All job commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  list     List detached CLI jobs")
	fmt.Println("  get      Show a detached job")
	fmt.Println("  wait     Wait for a detached job to finish")
	fmt.Println("  logs     Print stdout/stderr captured for a detached job")
	fmt.Println("\nExamples:")
	fmt.Println("  gs jobs list --json")
	fmt.Println("  gs jobs get job_123 --json")
	fmt.Println("  gs jobs wait job_123 --timeout 2m --json")
	fmt.Println("  gs jobs logs job_123 --json")
}

func printDoctorHelp() {
	fmt.Println("Usage: gs doctor [options]")
	fmt.Println("Check auth, slice binding, cache, and service health.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs doctor --json")
}

func printContextHelp() {
	fmt.Println("Usage: gs context [options]")
	fmt.Println("Print agent-friendly current auth, checkout, and changeset context.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs context --json")
}

func printLoginHelp() {
	fmt.Println("Usage: gs login [status|<username>] [options]")
	fmt.Println("Log in with stored auth, show current auth status, or use a legacy username.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json              Print structured JSON output")
	fmt.Println("  --non-interactive   Fail instead of opening an interactive flow")
	fmt.Println("\nExamples:")
	fmt.Println("  gs login status --json")
	fmt.Println("  gs login --non-interactive --json")
}

func printLogoutHelp() {
	fmt.Println("Usage: gs logout [options]")
	fmt.Println("Clear stored bearer credentials or legacy auth.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs logout --json")
}

func printStatusHelp() {
	fmt.Println("Usage: gs status [options]")
	fmt.Println("Legacy alias for gs slice status.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json     Print structured JSON output")
	fmt.Println("  --remote   Include remote slice status")
	fmt.Println("\nExamples:")
	fmt.Println("  gs status --json")
}

func printInitHelp() {
	fmt.Println("Usage: gs init <slice-id> [options]")
	fmt.Println("Legacy alias for gs slice bind.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs init root --json")
}

func printLogHelp() {
	fmt.Println("Usage: gs log [<slice-id>] [options]")
	fmt.Println("Legacy alias for gs slice history.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs log --json")
}

func printRootHelp() {
	fmt.Println("Usage: gs root [options]")
	fmt.Println("Legacy alias for gs slice root.")
	fmt.Println("\nOptions:")
	fmt.Println("  --json   Print structured JSON output")
	fmt.Println("\nExamples:")
	fmt.Println("  gs root --json")
}

func printChangesetHelp() {
	fmt.Println("Usage: gs changeset <command> [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  create    Create a new changeset from local modifications")
	fmt.Println("  show      Show the tracked or specified changeset")
	fmt.Println("  review    Review a changeset")
	fmt.Println("  merge     Merge a changeset into the slice")
	fmt.Println("  close     Close a changeset without merging")
	fmt.Println("  rebase    Rebase a changeset onto the latest slice head")
	fmt.Println("  list      List changesets for the current slice")
	fmt.Println("\nExamples:")
	fmt.Println("  gs changeset create --message \"update settings\" --json")
	fmt.Println("  gs changeset create --replace-tracked --message \"new attempt\" --json")
	fmt.Println("  gs changeset show --json")
	fmt.Println("  gs changeset review cs_123 --json")
	fmt.Println("  gs changeset rebase cs_123 --json")
	fmt.Println("  gs changeset merge --wait --json")
	fmt.Println("  gs changeset merge --force --reason \"emergency fix\"")
	fmt.Println("  gs changeset close --json")
}

func printConflictHelp() {
	fmt.Println("Usage: gs conflict <command> [options]")
	fmt.Println("Most conflict commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  list       List conflicts for the current or specified slice")
	fmt.Println("  resolve    Resolve a conflict in favor of a slice")
	fmt.Println("  show       Show details for a conflicted file")
	fmt.Println("\nExamples:")
	fmt.Println("  gs conflict list --json")
	fmt.Println("  gs conflict show file_123 --json")
	fmt.Println("  gs conflict resolve file_123 --prefer nic/ui-refresh --json")
}

func printImportHelp() {
	fmt.Println("Usage: gs import <command> [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  git        Import a remote git repository into your home tree")
	fmt.Println("\nExamples:")
	fmt.Println("  gs import git https://github.com/org/repo.git")
}

func printRepoHelp() {
	fmt.Println("Usage: gs repo <command> [options]")
	fmt.Println("Most repo commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  ensure   Ensure a remote repo binding exists at an absolute home path")
	fmt.Println("  import   Import a remote repository into an absolute home path and create a binding")
	fmt.Println("  list     List your remote repo bindings")
	fmt.Println("  status   Show the binding configured for an absolute home path")
	fmt.Println("  pull     Pull the latest remote snapshot into the bound home path")
	fmt.Println("  push     Push the bound home path back to the tracked remote branch")
	fmt.Println("  unlink   Remove the binding from an absolute home path")
	fmt.Println("\nExamples:")
	fmt.Println("  gs repo ensure https://github.com/org/repo.git /nic/vendor/repo --json")
	fmt.Println("  gs repo list --json")
	fmt.Println("  gs repo pull /nic/vendor/repo --detach --json")
	fmt.Println("  gs repo push /nic/vendor/repo --detach --json")
}

func printFileHelp() {
	fmt.Println("Usage: gs file <command> [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  ls             List directory entries")
	fmt.Println("  cat            Show file contents")
	fmt.Println("  history        Show file change history")
	fmt.Println("  dir-history    Show directory change history")
	fmt.Println("  commit-changes Show all file changes in a commit")
	fmt.Println("\nExamples:")
	fmt.Println("  gs file ls apps/web --slice root --json")
	fmt.Println("  gs file cat README.md --slice root --json")
	fmt.Println("  gs file history apps/web/main.go --slice root --json")
	fmt.Println("  gs file commit-changes <commit-hash> --json")
}

func printFilesystemHelp() {
	fmt.Println("Usage: gs fs <command> [options]")
	fmt.Println("Use gs fs batch with JSON/JSONL for machine-driven bulk edits.")
	fmt.Println("\nCommands:")
	fmt.Println("  cat          Print file content from an absolute home path")
	fmt.Println("  write        Write an absolute home path from stdin or a local file")
	fmt.Println("  batch        Execute multiple fs mutations from JSON/JSONL in one commit")
	fmt.Println("  ls           List an absolute home directory")
	fmt.Println("  mkdir        Create an absolute home directory")
	fmt.Println("  ensure-dir   Ensure an absolute home directory exists")
	fmt.Println("  rm           Delete an absolute home path")
	fmt.Println("  mv           Move or rename an absolute home path")
	fmt.Println("  cp           Copy an absolute home path")
	fmt.Println("  glob         Find files by absolute home pattern")
	fmt.Println("  search       Search file contents in the home slice (use --regex for regex mode)")
	fmt.Println("  stat         Show metadata for an absolute home path")
	fmt.Println("  visibility   Inspect or change path visibility")
	fmt.Println("  snapshot     Create a snapshot")
	fmt.Println("  snapshots    List snapshots")
	fmt.Println("  log          Show home-slice commit history")
	fmt.Println("  restore      Restore a snapshot")
	fmt.Println("  diff         Show changes since a snapshot")
	fmt.Println("  show         Show indexed file changes for a commit")
	fmt.Println("  shell        Open an interactive home-slice shell")
	fmt.Println("  sync         Sync a local directory to or from an absolute home path")
	fmt.Println("  upload       Upload a local directory tree to an absolute home path")
	fmt.Println("  download     Download an absolute home path to a local directory")
	fmt.Println("\nExamples:")
	fmt.Println("  gs fs cat /nic/app/config.json --json")
	fmt.Println("  gs fs write /nic/app/config.json -f config.json --json")
	fmt.Println("  gs fs ensure-dir /nic/app/config --json")
	fmt.Println("  gs fs visibility get /nic/app/config.json --json")
	fmt.Println("  gs fs visibility set /nic/app public --recursive --json")
	fmt.Println("  cat ops.jsonl | gs fs batch -m \"bulk update\"")
	fmt.Println("  gs fs search settings --glob /nic/app/** --json")
	fmt.Println("  gs fs sync --direction push ./site /nic/site --detach --json")
	fmt.Println("  gs fs upload ./project /nic/project --include-ignored")
}

func printSliceVisibilityHelp() {
	fmt.Println("Usage: gs slice visibility <command> [options]")
	fmt.Println("All visibility commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  get     Show the current visibility for a slice")
	fmt.Println("  set     Update a slice visibility and optionally propagate path visibility")
	fmt.Println("\nExamples:")
	fmt.Println("  gs slice visibility get nic/ui-refresh --json")
	fmt.Println("  gs slice visibility set nic/ui-refresh public --propagate public --json")
	fmt.Println("  gs slice visibility set nic/ui-refresh private --json")
}

func printFilesystemVisibilityHelp() {
	fmt.Println("Usage: gs fs visibility <command> [options]")
	fmt.Println("All visibility commands support --json.")
	fmt.Println("\nCommands:")
	fmt.Println("  get     Show the current visibility for an absolute home path")
	fmt.Println("  set     Update visibility for an absolute home path")
	fmt.Println("\nExamples:")
	fmt.Println("  gs fs visibility get /nic/app/config.json --json")
	fmt.Println("  gs fs visibility set /nic/app/config.json public --json")
	fmt.Println("  gs fs visibility set /nic/app public --recursive --json")
}
