// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: admin_service.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchMergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSlices     *int32                 `protobuf:"varint,1,opt,name=max_slices,json=maxSlices,proto3,oneof" json:"max_slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMergeRequest) Reset() {
	*x = BatchMergeRequest{}
	mi := &file_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMergeRequest) ProtoMessage() {}

func (x *BatchMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMergeRequest.ProtoReflect.Descriptor instead.
func (*BatchMergeRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchMergeRequest) GetMaxSlices() int32 {
	if x != nil && x.MaxSlices != nil {
		return *x.MaxSlices
	}
	return 0
}

type BatchMergeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalCommitHash string                 `protobuf:"bytes,1,opt,name=global_commit_hash,json=globalCommitHash,proto3" json:"global_commit_hash,omitempty"`
	MergedSliceCount int32                  `protobuf:"varint,2,opt,name=merged_slice_count,json=mergedSliceCount,proto3" json:"merged_slice_count,omitempty"`
	MergedSliceIds   []string               `protobuf:"bytes,3,rep,name=merged_slice_ids,json=mergedSliceIds,proto3" json:"merged_slice_ids,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchMergeResponse) Reset() {
	*x = BatchMergeResponse{}
	mi := &file_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMergeResponse) ProtoMessage() {}

func (x *BatchMergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMergeResponse.ProtoReflect.Descriptor instead.
func (*BatchMergeResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchMergeResponse) GetGlobalCommitHash() string {
	if x != nil {
		return x.GlobalCommitHash
	}
	return ""
}

func (x *BatchMergeResponse) GetMergedSliceCount() int32 {
	if x != nil {
		return x.MergedSliceCount
	}
	return 0
}

func (x *BatchMergeResponse) GetMergedSliceIds() []string {
	if x != nil {
		return x.MergedSliceIds
	}
	return nil
}

func (x *BatchMergeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ListSlicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesRequest) Reset() {
	*x = ListSlicesRequest{}
	mi := &file_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesRequest) ProtoMessage() {}

func (x *ListSlicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesRequest.ProtoReflect.Descriptor instead.
func (*ListSlicesRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListSlicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSlicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSlicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*SliceInfo           `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesResponse) Reset() {
	*x = ListSlicesResponse{}
	mi := &file_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesResponse) ProtoMessage() {}

func (x *ListSlicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesResponse.ProtoReflect.Descriptor instead.
func (*ListSlicesResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListSlicesResponse) GetSlices() []*SliceInfo {
	if x != nil {
		return x.Slices
	}
	return nil
}

type SliceInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SliceId            string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	LatestCommitHash   string                 `protobuf:"bytes,2,opt,name=latest_commit_hash,json=latestCommitHash,proto3" json:"latest_commit_hash,omitempty"`
	ModifiedFilesCount int32                  `protobuf:"varint,3,opt,name=modified_files_count,json=modifiedFilesCount,proto3" json:"modified_files_count,omitempty"`
	LastModified       int64                  `protobuf:"varint,4,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SliceInfo) Reset() {
	*x = SliceInfo{}
	mi := &file_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceInfo) ProtoMessage() {}

func (x *SliceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceInfo.ProtoReflect.Descriptor instead.
func (*SliceInfo) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *SliceInfo) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *SliceInfo) GetLatestCommitHash() string {
	if x != nil {
		return x.LatestCommitHash
	}
	return ""
}

func (x *SliceInfo) GetModifiedFilesCount() int32 {
	if x != nil {
		return x.ModifiedFilesCount
	}
	return 0
}

func (x *SliceInfo) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

type ConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       *string                `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3,oneof" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictsRequest) Reset() {
	*x = ConflictsRequest{}
	mi := &file_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsRequest) ProtoMessage() {}

func (x *ConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsRequest.ProtoReflect.Descriptor instead.
func (*ConflictsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConflictsRequest) GetSliceId() string {
	if x != nil && x.SliceId != nil {
		return *x.SliceId
	}
	return ""
}

type ConflictsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Conflicts      []*Conflict            `protobuf:"bytes,1,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	TotalConflicts int32                  `protobuf:"varint,2,opt,name=total_conflicts,json=totalConflicts,proto3" json:"total_conflicts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConflictsResponse) Reset() {
	*x = ConflictsResponse{}
	mi := &file_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsResponse) ProtoMessage() {}

func (x *ConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsResponse.ProtoReflect.Descriptor instead.
func (*ConflictsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *ConflictsResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *ConflictsResponse) GetTotalConflicts() int32 {
	if x != nil {
		return x.TotalConflicts
	}
	return 0
}

type Conflict struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FileId              string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ConflictingSliceIds []string               `protobuf:"bytes,2,rep,name=conflicting_slice_ids,json=conflictingSliceIds,proto3" json:"conflicting_slice_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *Conflict) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Conflict) GetConflictingSliceIds() []string {
	if x != nil {
		return x.ConflictingSliceIds
	}
	return nil
}

type GlobalStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeHistory bool                   `protobuf:"varint,1,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalStateRequest) Reset() {
	*x = GlobalStateRequest{}
	mi := &file_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStateRequest) ProtoMessage() {}

func (x *GlobalStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStateRequest.ProtoReflect.Descriptor instead.
func (*GlobalStateRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *GlobalStateRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

type GlobalStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalCommitHash string                 `protobuf:"bytes,1,opt,name=global_commit_hash,json=globalCommitHash,proto3" json:"global_commit_hash,omitempty"`
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	History          []*GlobalCommitHistory `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GlobalStateResponse) Reset() {
	*x = GlobalStateResponse{}
	mi := &file_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStateResponse) ProtoMessage() {}

func (x *GlobalStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStateResponse.ProtoReflect.Descriptor instead.
func (*GlobalStateResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{9}
}

func (x *GlobalStateResponse) GetGlobalCommitHash() string {
	if x != nil {
		return x.GlobalCommitHash
	}
	return ""
}

func (x *GlobalStateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GlobalStateResponse) GetHistory() []*GlobalCommitHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type GlobalCommitHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommitHash     string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MergedSliceIds []string               `protobuf:"bytes,3,rep,name=merged_slice_ids,json=mergedSliceIds,proto3" json:"merged_slice_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalCommitHistory) Reset() {
	*x = GlobalCommitHistory{}
	mi := &file_admin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalCommitHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalCommitHistory) ProtoMessage() {}

func (x *GlobalCommitHistory) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalCommitHistory.ProtoReflect.Descriptor instead.
func (*GlobalCommitHistory) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalCommitHistory) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *GlobalCommitHistory) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GlobalCommitHistory) GetMergedSliceIds() []string {
	if x != nil {
		return x.MergedSliceIds
	}
	return nil
}

type WatchConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       *string                `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3,oneof" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConflictsRequest) Reset() {
	*x = WatchConflictsRequest{}
	mi := &file_admin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConflictsRequest) ProtoMessage() {}

func (x *WatchConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConflictsRequest.ProtoReflect.Descriptor instead.
func (*WatchConflictsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{11}
}

func (x *WatchConflictsRequest) GetSliceId() string {
	if x != nil && x.SliceId != nil {
		return *x.SliceId
	}
	return ""
}

type ConflictUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewConflicts      []*Conflict            `protobuf:"bytes,1,rep,name=new_conflicts,json=newConflicts,proto3" json:"new_conflicts,omitempty"`
	ResolvedConflicts []*Conflict            `protobuf:"bytes,2,rep,name=resolved_conflicts,json=resolvedConflicts,proto3" json:"resolved_conflicts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConflictUpdate) Reset() {
	*x = ConflictUpdate{}
	mi := &file_admin_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictUpdate) ProtoMessage() {}

func (x *ConflictUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictUpdate.ProtoReflect.Descriptor instead.
func (*ConflictUpdate) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{12}
}

func (x *ConflictUpdate) GetNewConflicts() []*Conflict {
	if x != nil {
		return x.NewConflicts
	}
	return nil
}

func (x *ConflictUpdate) GetResolvedConflicts() []*Conflict {
	if x != nil {
		return x.ResolvedConflicts
	}
	return nil
}

var File_admin_service_proto protoreflect.FileDescriptor

const file_admin_service_proto_rawDesc = "" +
	"\n" +
	"\x13admin_service.proto\x12\badmin.v1\"F\n" +
	"\x11BatchMergeRequest\x12\"\n" +
	"\n" +
	"max_slices\x18\x01 \x01(\x05H\x00R\tmaxSlices\x88\x01\x01B\r\n" +
	"\v_max_slices\"\xb8\x01\n" +
	"\x12BatchMergeResponse\x12,\n" +
	"\x12global_commit_hash\x18\x01 \x01(\tR\x10globalCommitHash\x12,\n" +
	"\x12merged_slice_count\x18\x02 \x01(\x05R\x10mergedSliceCount\x12(\n" +
	"\x10merged_slice_ids\x18\x03 \x03(\tR\x0emergedSliceIds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"A\n" +
	"\x11ListSlicesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"A\n" +
	"\x12ListSlicesResponse\x12+\n" +
	"\x06slices\x18\x01 \x03(\v2\x13.admin.v1.SliceInfoR\x06slices\"\xab\x01\n" +
	"\tSliceInfo\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12,\n" +
	"\x12latest_commit_hash\x18\x02 \x01(\tR\x10latestCommitHash\x120\n" +
	"\x14modified_files_count\x18\x03 \x01(\x05R\x12modifiedFilesCount\x12#\n" +
	"\rlast_modified\x18\x04 \x01(\x03R\flastModified\"?\n" +
	"\x10ConflictsRequest\x12\x1e\n" +
	"\bslice_id\x18\x01 \x01(\tH\x00R\asliceId\x88\x01\x01B\v\n" +
	"\t_slice_id\"n\n" +
	"\x11ConflictsResponse\x120\n" +
	"\tconflicts\x18\x01 \x03(\v2\x12.admin.v1.ConflictR\tconflicts\x12'\n" +
	"\x0ftotal_conflicts\x18\x02 \x01(\x05R\x0etotalConflicts\"W\n" +
	"\bConflict\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x122\n" +
	"\x15conflicting_slice_ids\x18\x02 \x03(\tR\x13conflictingSliceIds\"=\n" +
	"\x12GlobalStateRequest\x12'\n" +
	"\x0finclude_history\x18\x01 \x01(\bR\x0eincludeHistory\"\x9a\x01\n" +
	"\x13GlobalStateResponse\x12,\n" +
	"\x12global_commit_hash\x18\x01 \x01(\tR\x10globalCommitHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x127\n" +
	"\ahistory\x18\x03 \x03(\v2\x1d.admin.v1.GlobalCommitHistoryR\ahistory\"~\n" +
	"\x13GlobalCommitHistory\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10merged_slice_ids\x18\x03 \x03(\tR\x0emergedSliceIds\"D\n" +
	"\x15WatchConflictsRequest\x12\x1e\n" +
	"\bslice_id\x18\x01 \x01(\tH\x00R\asliceId\x88\x01\x01B\v\n" +
	"\t_slice_id\"\x8c\x01\n" +
	"\x0eConflictUpdate\x127\n" +
	"\rnew_conflicts\x18\x01 \x03(\v2\x12.admin.v1.ConflictR\fnewConflicts\x12A\n" +
	"\x12resolved_conflicts\x18\x02 \x03(\v2\x12.admin.v1.ConflictR\x11resolvedConflicts2\x87\x03\n" +
	"\fAdminService\x12G\n" +
	"\n" +
	"BatchMerge\x12\x1b.admin.v1.BatchMergeRequest\x1a\x1c.admin.v1.BatchMergeResponse\x12G\n" +
	"\n" +
	"ListSlices\x12\x1b.admin.v1.ListSlicesRequest\x1a\x1c.admin.v1.ListSlicesResponse\x12G\n" +
	"\fGetConflicts\x12\x1a.admin.v1.ConflictsRequest\x1a\x1b.admin.v1.ConflictsResponse\x12M\n" +
	"\x0eGetGlobalState\x12\x1c.admin.v1.GlobalStateRequest\x1a\x1d.admin.v1.GlobalStateResponse\x12M\n" +
	"\x0eWatchConflicts\x12\x1f.admin.v1.WatchConflictsRequest\x1a\x18.admin.v1.ConflictUpdate0\x01B)Z'github.com/niczy/gitslice/proto;adminv1b\x06proto3"

var (
	file_admin_service_proto_rawDescOnce sync.Once
	file_admin_service_proto_rawDescData []byte
)

func file_admin_service_proto_rawDescGZIP() []byte {
	file_admin_service_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)))
	})
	return file_admin_service_proto_rawDescData
}

var file_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_admin_service_proto_goTypes = []any{
	(*BatchMergeRequest)(nil),     // 0: admin.v1.BatchMergeRequest
	(*BatchMergeResponse)(nil),    // 1: admin.v1.BatchMergeResponse
	(*ListSlicesRequest)(nil),     // 2: admin.v1.ListSlicesRequest
	(*ListSlicesResponse)(nil),    // 3: admin.v1.ListSlicesResponse
	(*SliceInfo)(nil),             // 4: admin.v1.SliceInfo
	(*ConflictsRequest)(nil),      // 5: admin.v1.ConflictsRequest
	(*ConflictsResponse)(nil),     // 6: admin.v1.ConflictsResponse
	(*Conflict)(nil),              // 7: admin.v1.Conflict
	(*GlobalStateRequest)(nil),    // 8: admin.v1.GlobalStateRequest
	(*GlobalStateResponse)(nil),   // 9: admin.v1.GlobalStateResponse
	(*GlobalCommitHistory)(nil),   // 10: admin.v1.GlobalCommitHistory
	(*WatchConflictsRequest)(nil), // 11: admin.v1.WatchConflictsRequest
	(*ConflictUpdate)(nil),        // 12: admin.v1.ConflictUpdate
}
var file_admin_service_proto_depIdxs = []int32{
	4,  // 0: admin.v1.ListSlicesResponse.slices:type_name -> admin.v1.SliceInfo
	7,  // 1: admin.v1.ConflictsResponse.conflicts:type_name -> admin.v1.Conflict
	10, // 2: admin.v1.GlobalStateResponse.history:type_name -> admin.v1.GlobalCommitHistory
	7,  // 3: admin.v1.ConflictUpdate.new_conflicts:type_name -> admin.v1.Conflict
	7,  // 4: admin.v1.ConflictUpdate.resolved_conflicts:type_name -> admin.v1.Conflict
	0,  // 5: admin.v1.AdminService.BatchMerge:input_type -> admin.v1.BatchMergeRequest
	2,  // 6: admin.v1.AdminService.ListSlices:input_type -> admin.v1.ListSlicesRequest
	5,  // 7: admin.v1.AdminService.GetConflicts:input_type -> admin.v1.ConflictsRequest
	8,  // 8: admin.v1.AdminService.GetGlobalState:input_type -> admin.v1.GlobalStateRequest
	11, // 9: admin.v1.AdminService.WatchConflicts:input_type -> admin.v1.WatchConflictsRequest
	1,  // 10: admin.v1.AdminService.BatchMerge:output_type -> admin.v1.BatchMergeResponse
	3,  // 11: admin.v1.AdminService.ListSlices:output_type -> admin.v1.ListSlicesResponse
	6,  // 12: admin.v1.AdminService.GetConflicts:output_type -> admin.v1.ConflictsResponse
	9,  // 13: admin.v1.AdminService.GetGlobalState:output_type -> admin.v1.GlobalStateResponse
	12, // 14: admin.v1.AdminService.WatchConflicts:output_type -> admin.v1.ConflictUpdate
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_admin_service_proto_init() }
func file_admin_service_proto_init() {
	if File_admin_service_proto != nil {
		return
	}
	file_admin_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_admin_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_depIdxs,
		MessageInfos:      file_admin_service_proto_msgTypes,
	}.Build()
	File_admin_service_proto = out.File
	file_admin_service_proto_goTypes = nil
	file_admin_service_proto_depIdxs = nil
}
