// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: admin_service.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminService_BatchMerge_FullMethodName      = "/admin.v1.AdminService/BatchMerge"
	AdminService_CreateSlice_FullMethodName     = "/admin.v1.AdminService/CreateSlice"
	AdminService_ListSlices_FullMethodName      = "/admin.v1.AdminService/ListSlices"
	AdminService_GetConflicts_FullMethodName    = "/admin.v1.AdminService/GetConflicts"
	AdminService_ResolveConflict_FullMethodName = "/admin.v1.AdminService/ResolveConflict"
	AdminService_GetGlobalState_FullMethodName  = "/admin.v1.AdminService/GetGlobalState"
	AdminService_WatchConflicts_FullMethodName  = "/admin.v1.AdminService/WatchConflicts"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// Trigger batch merge to global
	BatchMerge(ctx context.Context, in *BatchMergeRequest, opts ...grpc.CallOption) (*BatchMergeResponse, error)
	// Create a new slice
	CreateSlice(ctx context.Context, in *CreateSliceRequest, opts ...grpc.CallOption) (*CreateSliceResponse, error)
	// List all active slices
	ListSlices(ctx context.Context, in *ListSlicesRequest, opts ...grpc.CallOption) (*ListSlicesResponse, error)
	// Get current conflicts across slices
	GetConflicts(ctx context.Context, in *ConflictsRequest, opts ...grpc.CallOption) (*ConflictsResponse, error)
	// Resolve a conflict by choosing a preferred slice
	ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error)
	// Get global state
	GetGlobalState(ctx context.Context, in *GlobalStateRequest, opts ...grpc.CallOption) (*GlobalStateResponse, error)
	// Stream conflict updates (bidirectional streaming)
	WatchConflicts(ctx context.Context, in *WatchConflictsRequest, opts ...grpc.CallOption) (AdminService_WatchConflictsClient, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) BatchMerge(ctx context.Context, in *BatchMergeRequest, opts ...grpc.CallOption) (*BatchMergeResponse, error) {
	out := new(BatchMergeResponse)
	err := c.cc.Invoke(ctx, AdminService_BatchMerge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) CreateSlice(ctx context.Context, in *CreateSliceRequest, opts ...grpc.CallOption) (*CreateSliceResponse, error) {
	out := new(CreateSliceResponse)
	err := c.cc.Invoke(ctx, AdminService_CreateSlice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListSlices(ctx context.Context, in *ListSlicesRequest, opts ...grpc.CallOption) (*ListSlicesResponse, error) {
	out := new(ListSlicesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListSlices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetConflicts(ctx context.Context, in *ConflictsRequest, opts ...grpc.CallOption) (*ConflictsResponse, error) {
	out := new(ConflictsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetConflicts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error) {
	out := new(ResolveConflictResponse)
	err := c.cc.Invoke(ctx, AdminService_ResolveConflict_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetGlobalState(ctx context.Context, in *GlobalStateRequest, opts ...grpc.CallOption) (*GlobalStateResponse, error) {
	out := new(GlobalStateResponse)
	err := c.cc.Invoke(ctx, AdminService_GetGlobalState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) WatchConflicts(ctx context.Context, in *WatchConflictsRequest, opts ...grpc.CallOption) (AdminService_WatchConflictsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_WatchConflicts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceWatchConflictsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AdminService_WatchConflictsClient interface {
	Recv() (*ConflictUpdate, error)
	grpc.ClientStream
}

type adminServiceWatchConflictsClient struct {
	grpc.ClientStream
}

func (x *adminServiceWatchConflictsClient) Recv() (*ConflictUpdate, error) {
	m := new(ConflictUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	// Trigger batch merge to global
	BatchMerge(context.Context, *BatchMergeRequest) (*BatchMergeResponse, error)
	// Create a new slice
	CreateSlice(context.Context, *CreateSliceRequest) (*CreateSliceResponse, error)
	// List all active slices
	ListSlices(context.Context, *ListSlicesRequest) (*ListSlicesResponse, error)
	// Get current conflicts across slices
	GetConflicts(context.Context, *ConflictsRequest) (*ConflictsResponse, error)
	// Resolve a conflict by choosing a preferred slice
	ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error)
	// Get global state
	GetGlobalState(context.Context, *GlobalStateRequest) (*GlobalStateResponse, error)
	// Stream conflict updates (bidirectional streaming)
	WatchConflicts(*WatchConflictsRequest, AdminService_WatchConflictsServer) error
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) BatchMerge(context.Context, *BatchMergeRequest) (*BatchMergeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchMerge not implemented")
}
func (UnimplementedAdminServiceServer) CreateSlice(context.Context, *CreateSliceRequest) (*CreateSliceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlice not implemented")
}
func (UnimplementedAdminServiceServer) ListSlices(context.Context, *ListSlicesRequest) (*ListSlicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSlices not implemented")
}
func (UnimplementedAdminServiceServer) GetConflicts(context.Context, *ConflictsRequest) (*ConflictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConflicts not implemented")
}
func (UnimplementedAdminServiceServer) ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveConflict not implemented")
}
func (UnimplementedAdminServiceServer) GetGlobalState(context.Context, *GlobalStateRequest) (*GlobalStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalState not implemented")
}
func (UnimplementedAdminServiceServer) WatchConflicts(*WatchConflictsRequest, AdminService_WatchConflictsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchConflicts not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_BatchMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).BatchMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_BatchMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).BatchMerge(ctx, req.(*BatchMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_CreateSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateSlice(ctx, req.(*CreateSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListSlices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSlicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListSlices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListSlices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListSlices(ctx, req.(*ListSlicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetConflicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConflictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetConflicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetConflicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetConflicts(ctx, req.(*ConflictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResolveConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResolveConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResolveConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResolveConflict(ctx, req.(*ResolveConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetGlobalState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetGlobalState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetGlobalState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetGlobalState(ctx, req.(*GlobalStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_WatchConflicts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchConflictsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServiceServer).WatchConflicts(m, &adminServiceWatchConflictsServer{stream})
}

type AdminService_WatchConflictsServer interface {
	Send(*ConflictUpdate) error
	grpc.ServerStream
}

type adminServiceWatchConflictsServer struct {
	grpc.ServerStream
}

func (x *adminServiceWatchConflictsServer) Send(m *ConflictUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchMerge",
			Handler:    _AdminService_BatchMerge_Handler,
		},
		{
			MethodName: "CreateSlice",
			Handler:    _AdminService_CreateSlice_Handler,
		},
		{
			MethodName: "ListSlices",
			Handler:    _AdminService_ListSlices_Handler,
		},
		{
			MethodName: "GetConflicts",
			Handler:    _AdminService_GetConflicts_Handler,
		},
		{
			MethodName: "ResolveConflict",
			Handler:    _AdminService_ResolveConflict_Handler,
		},
		{
			MethodName: "GetGlobalState",
			Handler:    _AdminService_GetGlobalState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConflicts",
			Handler:       _AdminService_WatchConflicts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "admin_service.proto",
}
