// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.3
// source: admin_service.proto

package adminv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchMergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxSlices     int32                  `protobuf:"varint,1,opt,name=max_slices,json=maxSlices,proto3" json:"max_slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMergeRequest) Reset() {
	*x = BatchMergeRequest{}
	mi := &file_admin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMergeRequest) ProtoMessage() {}

func (x *BatchMergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMergeRequest.ProtoReflect.Descriptor instead.
func (*BatchMergeRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchMergeRequest) GetMaxSlices() int32 {
	if x != nil {
		return x.MaxSlices
	}
	return 0
}

type BatchMergeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalCommitHash string                 `protobuf:"bytes,1,opt,name=global_commit_hash,json=globalCommitHash,proto3" json:"global_commit_hash,omitempty"`
	MergedSliceCount int32                  `protobuf:"varint,2,opt,name=merged_slice_count,json=mergedSliceCount,proto3" json:"merged_slice_count,omitempty"`
	MergedSliceIds   []string               `protobuf:"bytes,3,rep,name=merged_slice_ids,json=mergedSliceIds,proto3" json:"merged_slice_ids,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchMergeResponse) Reset() {
	*x = BatchMergeResponse{}
	mi := &file_admin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMergeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMergeResponse) ProtoMessage() {}

func (x *BatchMergeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMergeResponse.ProtoReflect.Descriptor instead.
func (*BatchMergeResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchMergeResponse) GetGlobalCommitHash() string {
	if x != nil {
		return x.GlobalCommitHash
	}
	return ""
}

func (x *BatchMergeResponse) GetMergedSliceCount() int32 {
	if x != nil {
		return x.MergedSliceCount
	}
	return 0
}

func (x *BatchMergeResponse) GetMergedSliceIds() []string {
	if x != nil {
		return x.MergedSliceIds
	}
	return nil
}

func (x *BatchMergeResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictsRequest) Reset() {
	*x = ConflictsRequest{}
	mi := &file_admin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsRequest) ProtoMessage() {}

func (x *ConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsRequest.ProtoReflect.Descriptor instead.
func (*ConflictsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{2}
}

func (x *ConflictsRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type ConflictsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Conflicts      []*Conflict            `protobuf:"bytes,1,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	TotalConflicts int32                  `protobuf:"varint,2,opt,name=total_conflicts,json=totalConflicts,proto3" json:"total_conflicts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConflictsResponse) Reset() {
	*x = ConflictsResponse{}
	mi := &file_admin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictsResponse) ProtoMessage() {}

func (x *ConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictsResponse.ProtoReflect.Descriptor instead.
func (*ConflictsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConflictsResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *ConflictsResponse) GetTotalConflicts() int32 {
	if x != nil {
		return x.TotalConflicts
	}
	return 0
}

type ResolveConflictRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileId           string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	PreferredSliceId string                 `protobuf:"bytes,2,opt,name=preferred_slice_id,json=preferredSliceId,proto3" json:"preferred_slice_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveConflictRequest) Reset() {
	*x = ResolveConflictRequest{}
	mi := &file_admin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictRequest) ProtoMessage() {}

func (x *ResolveConflictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictRequest.ProtoReflect.Descriptor instead.
func (*ResolveConflictRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveConflictRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ResolveConflictRequest) GetPreferredSliceId() string {
	if x != nil {
		return x.PreferredSliceId
	}
	return ""
}

type ResolveConflictResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResolvedConflict *Conflict              `protobuf:"bytes,1,opt,name=resolved_conflict,json=resolvedConflict,proto3" json:"resolved_conflict,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveConflictResponse) Reset() {
	*x = ResolveConflictResponse{}
	mi := &file_admin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictResponse) ProtoMessage() {}

func (x *ResolveConflictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictResponse.ProtoReflect.Descriptor instead.
func (*ResolveConflictResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveConflictResponse) GetResolvedConflict() *Conflict {
	if x != nil {
		return x.ResolvedConflict
	}
	return nil
}

type Conflict struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FileId              string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ConflictingSliceIds []string               `protobuf:"bytes,2,rep,name=conflicting_slice_ids,json=conflictingSliceIds,proto3" json:"conflicting_slice_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_admin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{6}
}

func (x *Conflict) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *Conflict) GetConflictingSliceIds() []string {
	if x != nil {
		return x.ConflictingSliceIds
	}
	return nil
}

type GlobalStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeHistory bool                   `protobuf:"varint,1,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalStateRequest) Reset() {
	*x = GlobalStateRequest{}
	mi := &file_admin_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStateRequest) ProtoMessage() {}

func (x *GlobalStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStateRequest.ProtoReflect.Descriptor instead.
func (*GlobalStateRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{7}
}

func (x *GlobalStateRequest) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

type GlobalStateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GlobalCommitHash string                 `protobuf:"bytes,1,opt,name=global_commit_hash,json=globalCommitHash,proto3" json:"global_commit_hash,omitempty"`
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	History          []*GlobalCommitHistory `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GlobalStateResponse) Reset() {
	*x = GlobalStateResponse{}
	mi := &file_admin_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalStateResponse) ProtoMessage() {}

func (x *GlobalStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalStateResponse.ProtoReflect.Descriptor instead.
func (*GlobalStateResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{8}
}

func (x *GlobalStateResponse) GetGlobalCommitHash() string {
	if x != nil {
		return x.GlobalCommitHash
	}
	return ""
}

func (x *GlobalStateResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GlobalStateResponse) GetHistory() []*GlobalCommitHistory {
	if x != nil {
		return x.History
	}
	return nil
}

type GlobalCommitHistory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CommitHash     string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"`
	Timestamp      int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MergedSliceIds []string               `protobuf:"bytes,3,rep,name=merged_slice_ids,json=mergedSliceIds,proto3" json:"merged_slice_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GlobalCommitHistory) Reset() {
	*x = GlobalCommitHistory{}
	mi := &file_admin_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalCommitHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalCommitHistory) ProtoMessage() {}

func (x *GlobalCommitHistory) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalCommitHistory.ProtoReflect.Descriptor instead.
func (*GlobalCommitHistory) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{9}
}

func (x *GlobalCommitHistory) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *GlobalCommitHistory) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GlobalCommitHistory) GetMergedSliceIds() []string {
	if x != nil {
		return x.MergedSliceIds
	}
	return nil
}

type ListSlicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesRequest) Reset() {
	*x = ListSlicesRequest{}
	mi := &file_admin_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesRequest) ProtoMessage() {}

func (x *ListSlicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesRequest.ProtoReflect.Descriptor instead.
func (*ListSlicesRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListSlicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSlicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSlicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*SliceInfo           `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesResponse) Reset() {
	*x = ListSlicesResponse{}
	mi := &file_admin_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesResponse) ProtoMessage() {}

func (x *ListSlicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesResponse.ProtoReflect.Descriptor instead.
func (*ListSlicesResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListSlicesResponse) GetSlices() []*SliceInfo {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *ListSlicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ImportGitRepoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local filesystem path to a git checkout on the server host.
	RepoPath string `protobuf:"bytes,1,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	// Remote git URL to clone on the server host (e.g. a GitHub URL).
	// Exactly one of repo_path or repo_url must be set.
	RepoUrl string `protobuf:"bytes,8,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	// Git ref to import (default: "HEAD").
	Ref string `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	// Target slice ID (default: root_slice).
	SliceId string `protobuf:"bytes,3,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	// Mount path prefix for imported files (default: "/o/genesis/projects/<repo-name>").
	// The server will store file paths as "<mount_path>/<repo-relative-path>".
	MountPath string `protobuf:"bytes,4,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	// If true, reset the storage namespace before importing.
	ResetStorage bool `protobuf:"varint,5,opt,name=reset_storage,json=resetStorage,proto3" json:"reset_storage,omitempty"`
	// If true, import the first-parent linear history (recommended; merges are not represented).
	FirstParent bool `protobuf:"varint,6,opt,name=first_parent,json=firstParent,proto3" json:"first_parent,omitempty"`
	// Optional cap for number of commits imported (0 = no cap).
	MaxCommits    int32 `protobuf:"varint,7,opt,name=max_commits,json=maxCommits,proto3" json:"max_commits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportGitRepoRequest) Reset() {
	*x = ImportGitRepoRequest{}
	mi := &file_admin_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportGitRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGitRepoRequest) ProtoMessage() {}

func (x *ImportGitRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGitRepoRequest.ProtoReflect.Descriptor instead.
func (*ImportGitRepoRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{12}
}

func (x *ImportGitRepoRequest) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *ImportGitRepoRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *ImportGitRepoRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ImportGitRepoRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *ImportGitRepoRequest) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *ImportGitRepoRequest) GetResetStorage() bool {
	if x != nil {
		return x.ResetStorage
	}
	return false
}

func (x *ImportGitRepoRequest) GetFirstParent() bool {
	if x != nil {
		return x.FirstParent
	}
	return false
}

func (x *ImportGitRepoRequest) GetMaxCommits() int32 {
	if x != nil {
		return x.MaxCommits
	}
	return 0
}

type ImportGitRepoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ImportedCommits int32                  `protobuf:"varint,1,opt,name=imported_commits,json=importedCommits,proto3" json:"imported_commits,omitempty"`
	HeadCommitHash  string                 `protobuf:"bytes,2,opt,name=head_commit_hash,json=headCommitHash,proto3" json:"head_commit_hash,omitempty"`
	Warnings        []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImportGitRepoResponse) Reset() {
	*x = ImportGitRepoResponse{}
	mi := &file_admin_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportGitRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGitRepoResponse) ProtoMessage() {}

func (x *ImportGitRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGitRepoResponse.ProtoReflect.Descriptor instead.
func (*ImportGitRepoResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{13}
}

func (x *ImportGitRepoResponse) GetImportedCommits() int32 {
	if x != nil {
		return x.ImportedCommits
	}
	return 0
}

func (x *ImportGitRepoResponse) GetHeadCommitHash() string {
	if x != nil {
		return x.HeadCommitHash
	}
	return ""
}

func (x *ImportGitRepoResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type SliceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Owners        []string               `protobuf:"bytes,4,rep,name=owners,proto3" json:"owners,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FileCount     int32                  `protobuf:"varint,7,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	IsRoot        bool                   `protobuf:"varint,8,opt,name=is_root,json=isRoot,proto3" json:"is_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceInfo) Reset() {
	*x = SliceInfo{}
	mi := &file_admin_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceInfo) ProtoMessage() {}

func (x *SliceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceInfo.ProtoReflect.Descriptor instead.
func (*SliceInfo) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{14}
}

func (x *SliceInfo) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *SliceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SliceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SliceInfo) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *SliceInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SliceInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SliceInfo) GetFileCount() int32 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *SliceInfo) GetIsRoot() bool {
	if x != nil {
		return x.IsRoot
	}
	return false
}

type WatchConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchConflictsRequest) Reset() {
	*x = WatchConflictsRequest{}
	mi := &file_admin_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchConflictsRequest) ProtoMessage() {}

func (x *WatchConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchConflictsRequest.ProtoReflect.Descriptor instead.
func (*WatchConflictsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{15}
}

func (x *WatchConflictsRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type ConflictUpdate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewConflicts      []*Conflict            `protobuf:"bytes,1,rep,name=new_conflicts,json=newConflicts,proto3" json:"new_conflicts,omitempty"`
	ResolvedConflicts []*Conflict            `protobuf:"bytes,2,rep,name=resolved_conflicts,json=resolvedConflicts,proto3" json:"resolved_conflicts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConflictUpdate) Reset() {
	*x = ConflictUpdate{}
	mi := &file_admin_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictUpdate) ProtoMessage() {}

func (x *ConflictUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictUpdate.ProtoReflect.Descriptor instead.
func (*ConflictUpdate) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_rawDescGZIP(), []int{16}
}

func (x *ConflictUpdate) GetNewConflicts() []*Conflict {
	if x != nil {
		return x.NewConflicts
	}
	return nil
}

func (x *ConflictUpdate) GetResolvedConflicts() []*Conflict {
	if x != nil {
		return x.ResolvedConflicts
	}
	return nil
}

var File_admin_service_proto protoreflect.FileDescriptor

const file_admin_service_proto_rawDesc = "" +
	"\n" +
	"\x13admin_service.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x11BatchMergeRequest\x12\x1d\n" +
	"\n" +
	"max_slices\x18\x01 \x01(\x05R\tmaxSlices\"\xb8\x01\n" +
	"\x12BatchMergeResponse\x12,\n" +
	"\x12global_commit_hash\x18\x01 \x01(\tR\x10globalCommitHash\x12,\n" +
	"\x12merged_slice_count\x18\x02 \x01(\x05R\x10mergedSliceCount\x12(\n" +
	"\x10merged_slice_ids\x18\x03 \x03(\tR\x0emergedSliceIds\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"-\n" +
	"\x10ConflictsRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"n\n" +
	"\x11ConflictsResponse\x120\n" +
	"\tconflicts\x18\x01 \x03(\v2\x12.admin.v1.ConflictR\tconflicts\x12'\n" +
	"\x0ftotal_conflicts\x18\x02 \x01(\x05R\x0etotalConflicts\"_\n" +
	"\x16ResolveConflictRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12,\n" +
	"\x12preferred_slice_id\x18\x02 \x01(\tR\x10preferredSliceId\"Z\n" +
	"\x17ResolveConflictResponse\x12?\n" +
	"\x11resolved_conflict\x18\x01 \x01(\v2\x12.admin.v1.ConflictR\x10resolvedConflict\"W\n" +
	"\bConflict\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x122\n" +
	"\x15conflicting_slice_ids\x18\x02 \x03(\tR\x13conflictingSliceIds\"=\n" +
	"\x12GlobalStateRequest\x12'\n" +
	"\x0finclude_history\x18\x01 \x01(\bR\x0eincludeHistory\"\x9a\x01\n" +
	"\x13GlobalStateResponse\x12,\n" +
	"\x12global_commit_hash\x18\x01 \x01(\tR\x10globalCommitHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x127\n" +
	"\ahistory\x18\x03 \x03(\v2\x1d.admin.v1.GlobalCommitHistoryR\ahistory\"~\n" +
	"\x13GlobalCommitHistory\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12(\n" +
	"\x10merged_slice_ids\x18\x03 \x03(\tR\x0emergedSliceIds\"A\n" +
	"\x11ListSlicesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"W\n" +
	"\x12ListSlicesResponse\x12+\n" +
	"\x06slices\x18\x01 \x03(\v2\x13.admin.v1.SliceInfoR\x06slices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x83\x02\n" +
	"\x14ImportGitRepoRequest\x12\x1b\n" +
	"\trepo_path\x18\x01 \x01(\tR\brepoPath\x12\x19\n" +
	"\brepo_url\x18\b \x01(\tR\arepoUrl\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x19\n" +
	"\bslice_id\x18\x03 \x01(\tR\asliceId\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x04 \x01(\tR\tmountPath\x12#\n" +
	"\rreset_storage\x18\x05 \x01(\bR\fresetStorage\x12!\n" +
	"\ffirst_parent\x18\x06 \x01(\bR\vfirstParent\x12\x1f\n" +
	"\vmax_commits\x18\a \x01(\x05R\n" +
	"maxCommits\"\x88\x01\n" +
	"\x15ImportGitRepoResponse\x12)\n" +
	"\x10imported_commits\x18\x01 \x01(\x05R\x0fimportedCommits\x12(\n" +
	"\x10head_commit_hash\x18\x02 \x01(\tR\x0eheadCommitHash\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\"\xea\x01\n" +
	"\tSliceInfo\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06owners\x18\x04 \x03(\tR\x06owners\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"file_count\x18\a \x01(\x05R\tfileCount\x12\x17\n" +
	"\ais_root\x18\b \x01(\bR\x06isRoot\"2\n" +
	"\x15WatchConflictsRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"\x8c\x01\n" +
	"\x0eConflictUpdate\x127\n" +
	"\rnew_conflicts\x18\x01 \x03(\v2\x12.admin.v1.ConflictR\fnewConflicts\x12A\n" +
	"\x12resolved_conflicts\x18\x02 \x03(\v2\x12.admin.v1.ConflictR\x11resolvedConflicts2\xd6\x05\n" +
	"\fAdminService\x12j\n" +
	"\n" +
	"BatchMerge\x12\x1b.admin.v1.BatchMergeRequest\x1a\x1c.admin.v1.BatchMergeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/global/batch-merge\x12^\n" +
	"\fGetConflicts\x12\x1a.admin.v1.ConflictsRequest\x1a\x1b.admin.v1.ConflictsResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/conflicts\x12x\n" +
	"\x0fResolveConflict\x12 .admin.v1.ResolveConflictRequest\x1a!.admin.v1.ResolveConflictResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/conflicts:resolve\x12g\n" +
	"\x0eGetGlobalState\x12\x1c.admin.v1.GlobalStateRequest\x1a\x1d.admin.v1.GlobalStateResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/global/state\x12[\n" +
	"\n" +
	"ListSlices\x12\x1b.admin.v1.ListSlicesRequest\x1a\x1c.admin.v1.ListSlicesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/slices\x12k\n" +
	"\rImportGitRepo\x12\x1e.admin.v1.ImportGitRepoRequest\x1a\x1f.admin.v1.ImportGitRepoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/import/git\x12M\n" +
	"\x0eWatchConflicts\x12\x1f.admin.v1.WatchConflictsRequest\x1a\x18.admin.v1.ConflictUpdate0\x01B)Z'github.com/niczy/gitslice/proto;adminv1b\x06proto3"

var (
	file_admin_service_proto_rawDescOnce sync.Once
	file_admin_service_proto_rawDescData []byte
)

func file_admin_service_proto_rawDescGZIP() []byte {
	file_admin_service_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)))
	})
	return file_admin_service_proto_rawDescData
}

var file_admin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_admin_service_proto_goTypes = []any{
	(*BatchMergeRequest)(nil),       // 0: admin.v1.BatchMergeRequest
	(*BatchMergeResponse)(nil),      // 1: admin.v1.BatchMergeResponse
	(*ConflictsRequest)(nil),        // 2: admin.v1.ConflictsRequest
	(*ConflictsResponse)(nil),       // 3: admin.v1.ConflictsResponse
	(*ResolveConflictRequest)(nil),  // 4: admin.v1.ResolveConflictRequest
	(*ResolveConflictResponse)(nil), // 5: admin.v1.ResolveConflictResponse
	(*Conflict)(nil),                // 6: admin.v1.Conflict
	(*GlobalStateRequest)(nil),      // 7: admin.v1.GlobalStateRequest
	(*GlobalStateResponse)(nil),     // 8: admin.v1.GlobalStateResponse
	(*GlobalCommitHistory)(nil),     // 9: admin.v1.GlobalCommitHistory
	(*ListSlicesRequest)(nil),       // 10: admin.v1.ListSlicesRequest
	(*ListSlicesResponse)(nil),      // 11: admin.v1.ListSlicesResponse
	(*ImportGitRepoRequest)(nil),    // 12: admin.v1.ImportGitRepoRequest
	(*ImportGitRepoResponse)(nil),   // 13: admin.v1.ImportGitRepoResponse
	(*SliceInfo)(nil),               // 14: admin.v1.SliceInfo
	(*WatchConflictsRequest)(nil),   // 15: admin.v1.WatchConflictsRequest
	(*ConflictUpdate)(nil),          // 16: admin.v1.ConflictUpdate
}
var file_admin_service_proto_depIdxs = []int32{
	6,  // 0: admin.v1.ConflictsResponse.conflicts:type_name -> admin.v1.Conflict
	6,  // 1: admin.v1.ResolveConflictResponse.resolved_conflict:type_name -> admin.v1.Conflict
	9,  // 2: admin.v1.GlobalStateResponse.history:type_name -> admin.v1.GlobalCommitHistory
	14, // 3: admin.v1.ListSlicesResponse.slices:type_name -> admin.v1.SliceInfo
	6,  // 4: admin.v1.ConflictUpdate.new_conflicts:type_name -> admin.v1.Conflict
	6,  // 5: admin.v1.ConflictUpdate.resolved_conflicts:type_name -> admin.v1.Conflict
	0,  // 6: admin.v1.AdminService.BatchMerge:input_type -> admin.v1.BatchMergeRequest
	2,  // 7: admin.v1.AdminService.GetConflicts:input_type -> admin.v1.ConflictsRequest
	4,  // 8: admin.v1.AdminService.ResolveConflict:input_type -> admin.v1.ResolveConflictRequest
	7,  // 9: admin.v1.AdminService.GetGlobalState:input_type -> admin.v1.GlobalStateRequest
	10, // 10: admin.v1.AdminService.ListSlices:input_type -> admin.v1.ListSlicesRequest
	12, // 11: admin.v1.AdminService.ImportGitRepo:input_type -> admin.v1.ImportGitRepoRequest
	15, // 12: admin.v1.AdminService.WatchConflicts:input_type -> admin.v1.WatchConflictsRequest
	1,  // 13: admin.v1.AdminService.BatchMerge:output_type -> admin.v1.BatchMergeResponse
	3,  // 14: admin.v1.AdminService.GetConflicts:output_type -> admin.v1.ConflictsResponse
	5,  // 15: admin.v1.AdminService.ResolveConflict:output_type -> admin.v1.ResolveConflictResponse
	8,  // 16: admin.v1.AdminService.GetGlobalState:output_type -> admin.v1.GlobalStateResponse
	11, // 17: admin.v1.AdminService.ListSlices:output_type -> admin.v1.ListSlicesResponse
	13, // 18: admin.v1.AdminService.ImportGitRepo:output_type -> admin.v1.ImportGitRepoResponse
	16, // 19: admin.v1.AdminService.WatchConflicts:output_type -> admin.v1.ConflictUpdate
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_admin_service_proto_init() }
func file_admin_service_proto_init() {
	if File_admin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_service_proto_rawDesc), len(file_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_depIdxs,
		MessageInfos:      file_admin_service_proto_msgTypes,
	}.Build()
	File_admin_service_proto = out.File
	file_admin_service_proto_goTypes = nil
	file_admin_service_proto_depIdxs = nil
}
