import { Badge } from '../ui/badge.jsx';
import { Button } from '../ui/button.jsx';
import { Card, CardContent } from '../ui/card.jsx';

export default function AgentKeysCard({
  agentKeyFormError,
  agentKeyName,
  agentKeyPublicKey,
  agentKeySaving,
  agentKeys,
  agentKeysError,
  agentKeysLoading,
  onAgentKeyCreate,
  onAgentKeyNameChange,
  onAgentKeyPublicKeyChange,
  onAgentKeyRevoke,
  revokingKeyId,
}) {
  return (
    <Card className="border-border/70">
      <CardContent className="space-y-4 pt-6">
        <div className="space-y-2">
          <h3>Agent keys</h3>
          <p className="status">Enroll public keys for non-interactive <code>gs auth login --key</code> flows, then revoke them here when a machine should lose access.</p>
        </div>

        <form className="grid gap-4 rounded-lg border border-border/70 bg-background/40 p-4 md:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]" data-testid="settings-agent-key-form" onSubmit={onAgentKeyCreate}>
          <label className="space-y-2">
            <span className="text-sm font-medium text-foreground">Key name</span>
            <input
              className="h-11 w-full rounded-md border border-border bg-background px-3 text-sm text-foreground outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/40"
              data-testid="settings-agent-key-name"
              placeholder="codex-laptop"
              value={agentKeyName}
              onChange={(event) => onAgentKeyNameChange(event.target.value)}
            />
          </label>
          <label className="space-y-2">
            <span className="text-sm font-medium text-foreground">Public key</span>
            <textarea
              className="min-h-28 w-full rounded-md border border-border bg-background px-3 py-3 text-sm text-foreground outline-none transition focus:border-ring focus:ring-2 focus:ring-ring/40"
              data-testid="settings-agent-key-public-key"
              placeholder="Paste the .pub file generated by gs auth keygen"
              value={agentKeyPublicKey}
              onChange={(event) => onAgentKeyPublicKeyChange(event.target.value)}
            />
          </label>
          <div className="flex items-end">
            <Button data-testid="settings-agent-key-submit" type="submit" disabled={agentKeySaving}>
              {agentKeySaving ? 'Adding...' : 'Add key'}
            </Button>
          </div>
        </form>
        {agentKeyFormError && <div className="panel-error">{agentKeyFormError}</div>}

        {agentKeysLoading && <div className="panel-empty">Loading agent keys...</div>}
        {!agentKeysLoading && agentKeysError && <div className="panel-error">{agentKeysError}</div>}
        {!agentKeysLoading && !agentKeysError && agentKeys.length === 0 && (
          <div className="panel-empty" data-testid="settings-agent-keys-empty">
            No agent keys yet. Run <code>gs auth keygen --out ~/.config/gitslice/agent_ed25519</code> and paste the generated <code>.pub</code> file here.
          </div>
        )}
        {!agentKeysLoading && !agentKeysError && agentKeys.length > 0 && (
          <div className="space-y-3" data-testid="settings-agent-keys">
            {agentKeys.map((key) => (
              <div key={key.id} className="rounded-lg border border-border/70 bg-background/40 p-3">
                <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                  <div className="kv flex-1">
                    <div className="kv-row">
                      <span className="kv-key">Name</span>
                      <span className="kv-val">{key.name}</span>
                    </div>
                    <div className="kv-row">
                      <span className="kv-key">Key ID</span>
                      <span className="kv-val">{key.id}</span>
                    </div>
                    <div className="kv-row">
                      <span className="kv-key">Fingerprint</span>
                      <span className="kv-val break-all">{key.fingerprint}</span>
                    </div>
                    <div className="kv-row">
                      <span className="kv-key">Last used</span>
                      <span className="kv-val">{key.last_used_at || 'never'}</span>
                    </div>
                    <div className="kv-row">
                      <span className="kv-key">State</span>
                      <span className="kv-val">{key.revoked ? 'revoked' : 'active'}</span>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant={key.revoked ? 'outline' : 'secondary'}>{key.revoked ? 'Revoked' : 'Active'}</Badge>
                    <Button
                      type="button"
                      variant="destructive"
                      size="sm"
                      disabled={key.revoked || revokingKeyId === key.id}
                      onClick={() => onAgentKeyRevoke(key.id)}
                      data-testid={`settings-agent-key-revoke-${key.id}`}
                    >
                      {revokingKeyId === key.id ? 'Revoking...' : 'Revoke'}
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
