load("@rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "slice",
    srcs = [
        "genesis.go",
        "server.go",
    ],
    importpath = "github.com/niczy/gitslice/internal/services/slice",
    deps = [
        "//internal/common",
        "//internal/models",
        "//internal/storage",
        "//proto/slice",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
