// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent_service.proto

package agentv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SliceId        string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	E2BTemplateId  string                 `protobuf:"bytes,3,opt,name=e2b_template_id,json=e2bTemplateId,proto3" json:"e2b_template_id,omitempty"`
	E2BRegion      string                 `protobuf:"bytes,4,opt,name=e2b_region,json=e2bRegion,proto3" json:"e2b_region,omitempty"`
	IdleTimeoutSec int32                  `protobuf:"varint,5,opt,name=idle_timeout_sec,json=idleTimeoutSec,proto3" json:"idle_timeout_sec,omitempty"`
	TtlSec         int32                  `protobuf:"varint,6,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	Env            map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CreateSessionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateSessionRequest) GetE2BTemplateId() string {
	if x != nil {
		return x.E2BTemplateId
	}
	return ""
}

func (x *CreateSessionRequest) GetE2BRegion() string {
	if x != nil {
		return x.E2BRegion
	}
	return ""
}

func (x *CreateSessionRequest) GetIdleTimeoutSec() int32 {
	if x != nil {
		return x.IdleTimeoutSec
	}
	return 0
}

func (x *CreateSessionRequest) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

func (x *CreateSessionRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type WSConnectInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WSConnectInfo) Reset() {
	*x = WSConnectInfo{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WSConnectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WSConnectInfo) ProtoMessage() {}

func (x *WSConnectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WSConnectInfo.ProtoReflect.Descriptor instead.
func (*WSConnectInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *WSConnectInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WSConnectInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *WSConnectInfo) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type CreateSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SliceId        string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	E2BTemplateId  string                 `protobuf:"bytes,4,opt,name=e2b_template_id,json=e2bTemplateId,proto3" json:"e2b_template_id,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Ws             *WSConnectInfo         `protobuf:"bytes,6,opt,name=ws,proto3" json:"ws,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IdleTimeoutSec int32                  `protobuf:"varint,8,opt,name=idle_timeout_sec,json=idleTimeoutSec,proto3" json:"idle_timeout_sec,omitempty"`
	TtlSec         int32                  `protobuf:"varint,9,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *CreateSessionResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateSessionResponse) GetE2BTemplateId() string {
	if x != nil {
		return x.E2BTemplateId
	}
	return ""
}

func (x *CreateSessionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateSessionResponse) GetWs() *WSConnectInfo {
	if x != nil {
		return x.Ws
	}
	return nil
}

func (x *CreateSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateSessionResponse) GetIdleTimeoutSec() int32 {
	if x != nil {
		return x.IdleTimeoutSec
	}
	return 0
}

func (x *CreateSessionResponse) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type GetSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SliceId        string                 `protobuf:"bytes,2,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Provider       string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	E2BSandboxId   string                 `protobuf:"bytes,4,opt,name=e2b_sandbox_id,json=e2bSandboxId,proto3" json:"e2b_sandbox_id,omitempty"`
	State          string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	LastActivityAt string                 `protobuf:"bytes,6,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	IdleTimeoutSec int32                  `protobuf:"varint,7,opt,name=idle_timeout_sec,json=idleTimeoutSec,proto3" json:"idle_timeout_sec,omitempty"`
	TtlSec         int32                  `protobuf:"varint,8,opt,name=ttl_sec,json=ttlSec,proto3" json:"ttl_sec,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Runtime        *RuntimeInfo           `protobuf:"bytes,10,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *GetSessionResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetSessionResponse) GetE2BSandboxId() string {
	if x != nil {
		return x.E2BSandboxId
	}
	return ""
}

func (x *GetSessionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GetSessionResponse) GetLastActivityAt() string {
	if x != nil {
		return x.LastActivityAt
	}
	return ""
}

func (x *GetSessionResponse) GetIdleTimeoutSec() int32 {
	if x != nil {
		return x.IdleTimeoutSec
	}
	return 0
}

func (x *GetSessionResponse) GetTtlSec() int32 {
	if x != nil {
		return x.TtlSec
	}
	return 0
}

func (x *GetSessionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetSessionResponse) GetRuntime() *RuntimeInfo {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *StopSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_agent_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{7}
}

func (x *StopSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopSessionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type MintTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenRequest) Reset() {
	*x = MintTokenRequest{}
	mi := &file_agent_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenRequest) ProtoMessage() {}

func (x *MintTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenRequest.ProtoReflect.Descriptor instead.
func (*MintTokenRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{8}
}

func (x *MintTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MintTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintTokenResponse) Reset() {
	*x = MintTokenResponse{}
	mi := &file_agent_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintTokenResponse) ProtoMessage() {}

func (x *MintTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintTokenResponse.ProtoReflect.Descriptor instead.
func (*MintTokenResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{9}
}

func (x *MintTokenResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MintTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MintTokenResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Ts            string                 `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_agent_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{10}
}

func (x *EventEnvelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventEnvelope) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *EventEnvelope) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SinceSeq      uint64                 `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_agent_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListEventsRequest) GetSinceSeq() uint64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventEnvelope       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextSeq       uint64                 `protobuf:"varint,2,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_agent_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListEventsResponse) GetEvents() []*EventEnvelope {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\bagent.v1\x1a\x1cgoogle/api/annotations.proto\"\xca\x02\n" +
	"\x14CreateSessionRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12&\n" +
	"\x0fe2b_template_id\x18\x03 \x01(\tR\re2bTemplateId\x12\x1d\n" +
	"\n" +
	"e2b_region\x18\x04 \x01(\tR\te2bRegion\x12(\n" +
	"\x10idle_timeout_sec\x18\x05 \x01(\x05R\x0eidleTimeoutSec\x12\x17\n" +
	"\attl_sec\x18\x06 \x01(\x05R\x06ttlSec\x129\n" +
	"\x03env\x18\a \x03(\v2'.agent.v1.CreateSessionRequest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\rWSConnectInfo\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\xb6\x02\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12&\n" +
	"\x0fe2b_template_id\x18\x04 \x01(\tR\re2bTemplateId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12'\n" +
	"\x02ws\x18\x06 \x01(\v2\x17.agent.v1.WSConnectInfoR\x02ws\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12(\n" +
	"\x10idle_timeout_sec\x18\b \x01(\x05R\x0eidleTimeoutSec\x12\x17\n" +
	"\attl_sec\x18\t \x01(\x05R\x06ttlSec\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\")\n" +
	"\vRuntimeInfo\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"\xe3\x02\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bslice_id\x18\x02 \x01(\tR\asliceId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12$\n" +
	"\x0ee2b_sandbox_id\x18\x04 \x01(\tR\fe2bSandboxId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12(\n" +
	"\x10last_activity_at\x18\x06 \x01(\tR\x0elastActivityAt\x12(\n" +
	"\x10idle_timeout_sec\x18\a \x01(\x05R\x0eidleTimeoutSec\x12\x17\n" +
	"\attl_sec\x18\b \x01(\x05R\x06ttlSec\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12/\n" +
	"\aruntime\x18\n" +
	" \x01(\v2\x15.agent.v1.RuntimeInfoR\aruntime\"K\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"J\n" +
	"\x13StopSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"1\n" +
	"\x10MintTokenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"Z\n" +
	"\x11MintTokenResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"w\n" +
	"\rEventEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\tR\x02ts\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"e\n" +
	"\x11ListEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x04R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"`\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.agent.v1.EventEnvelopeR\x06events\x12\x19\n" +
	"\bnext_seq\x18\x02 \x01(\x04R\anextSeq2\xdc\x04\n" +
	"\fAgentService\x12o\n" +
	"\rCreateSession\x12\x1e.agent.v1.CreateSessionRequest\x1a\x1f.agent.v1.CreateSessionResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/agent-sessions\x12p\n" +
	"\n" +
	"GetSession\x12\x1b.agent.v1.GetSessionRequest\x1a\x1c.agent.v1.GetSessionResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/agent-sessions/{session_id}\x12{\n" +
	"\vStopSession\x12\x1c.agent.v1.StopSessionRequest\x1a\x1d.agent.v1.StopSessionResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/agent-sessions/{session_id}/stop\x12s\n" +
	"\tMintToken\x12\x1a.agent.v1.MintTokenRequest\x1a\x1b.agent.v1.MintTokenResponse\"-\x82\xd3\xe4\x93\x02'\"%/v1/agent-sessions/{session_id}/token\x12w\n" +
	"\n" +
	"ListEvents\x12\x1b.agent.v1.ListEventsRequest\x1a\x1c.agent.v1.ListEventsResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/agent-sessions/{session_id}/eventsB/Z-github.com/niczy/gitslice/proto/agent;agentv1b\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_agent_service_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: agent.v1.CreateSessionRequest
	(*WSConnectInfo)(nil),         // 1: agent.v1.WSConnectInfo
	(*CreateSessionResponse)(nil), // 2: agent.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 3: agent.v1.GetSessionRequest
	(*RuntimeInfo)(nil),           // 4: agent.v1.RuntimeInfo
	(*GetSessionResponse)(nil),    // 5: agent.v1.GetSessionResponse
	(*StopSessionRequest)(nil),    // 6: agent.v1.StopSessionRequest
	(*StopSessionResponse)(nil),   // 7: agent.v1.StopSessionResponse
	(*MintTokenRequest)(nil),      // 8: agent.v1.MintTokenRequest
	(*MintTokenResponse)(nil),     // 9: agent.v1.MintTokenResponse
	(*EventEnvelope)(nil),         // 10: agent.v1.EventEnvelope
	(*ListEventsRequest)(nil),     // 11: agent.v1.ListEventsRequest
	(*ListEventsResponse)(nil),    // 12: agent.v1.ListEventsResponse
	nil,                           // 13: agent.v1.CreateSessionRequest.EnvEntry
}
var file_agent_service_proto_depIdxs = []int32{
	13, // 0: agent.v1.CreateSessionRequest.env:type_name -> agent.v1.CreateSessionRequest.EnvEntry
	1,  // 1: agent.v1.CreateSessionResponse.ws:type_name -> agent.v1.WSConnectInfo
	4,  // 2: agent.v1.GetSessionResponse.runtime:type_name -> agent.v1.RuntimeInfo
	10, // 3: agent.v1.ListEventsResponse.events:type_name -> agent.v1.EventEnvelope
	0,  // 4: agent.v1.AgentService.CreateSession:input_type -> agent.v1.CreateSessionRequest
	3,  // 5: agent.v1.AgentService.GetSession:input_type -> agent.v1.GetSessionRequest
	6,  // 6: agent.v1.AgentService.StopSession:input_type -> agent.v1.StopSessionRequest
	8,  // 7: agent.v1.AgentService.MintToken:input_type -> agent.v1.MintTokenRequest
	11, // 8: agent.v1.AgentService.ListEvents:input_type -> agent.v1.ListEventsRequest
	2,  // 9: agent.v1.AgentService.CreateSession:output_type -> agent.v1.CreateSessionResponse
	5,  // 10: agent.v1.AgentService.GetSession:output_type -> agent.v1.GetSessionResponse
	7,  // 11: agent.v1.AgentService.StopSession:output_type -> agent.v1.StopSessionResponse
	9,  // 12: agent.v1.AgentService.MintToken:output_type -> agent.v1.MintTokenResponse
	12, // 13: agent.v1.AgentService.ListEvents:output_type -> agent.v1.ListEventsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
