load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "common",
    srcs = [
        "health.go",
        "init.go",
        "validation.go",
    ],
    importpath = "github.com/niczy/gitslice/internal/common",
    visibility = ["//visibility:public"],
    deps = ["//internal/storage"],
)
