#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVICE_LOG_DIR="${LOG_DIR:-./logs}"
NGINX_LOG_DIR="${NGINX_LOG_DIR:-/var/log/nginx}"
CORE_SERVICE_PORT="${CORE_SERVICE_PORT:-50051}"
GATEWAY_PORT="${GATEWAY_PORT:-8080}"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

cd "$REPO_ROOT"

log "Pulling latest changes..."
# Only pull if the current branch has an upstream tracking branch
if git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1; then
  git pull --ff-only
else
  log "No upstream tracking branch configured, skipping git pull"
fi

log "Starting services..."
LOG_DIR="$SERVICE_LOG_DIR" "$REPO_ROOT/ops/start_web_server.sh"

log "Verifying all services are healthy..."
# Final verification that all services are up before starting nginx
if ! curl -sf "http://localhost:${GATEWAY_PORT}/health" >/dev/null 2>&1; then
  log "ERROR: Gateway service is not healthy on port ${GATEWAY_PORT}"
  exit 1
fi
if ! nc -z localhost "${CORE_SERVICE_PORT}" 2>/dev/null; then
  log "ERROR: Core gRPC server is not listening on port ${CORE_SERVICE_PORT}"
  exit 1
fi
log "All services verified healthy"

setup_cronjob() {
  local cron_script="# Auto-generated by restart_all.sh
0 * * * * $(whoami) bash $REPO_ROOT/ops/restart_all.sh >> $REPO_ROOT/logs/cron.log 2>&1"

  local cron_file="/tmp/restart_all_cron"
  echo "$cron_script" > "$cron_file"
  crontab "$cron_file"
  rm "$cron_file"
  log "Installed hourly cronjob to user crontab"
}

setup_cronjob

log "Deployment complete!"
log "Services:"
log "  - Core gRPC server:       localhost:${CORE_SERVICE_PORT}"
log "  - HTTP Gateway:           localhost:${GATEWAY_PORT}"
log "  - Web preview:            localhost:4173"
